### ISSUE TITLE
PSNativeCommandErrorActionPreference default value is wrong

### ISSUE THREAD

**Issue by anthonyvdotbe** [MicrosoftDocs/PowerShell-Docs#10661]
### Type of issue

Outdated article

### Feedback

It says:

> Beginning in PowerShell 7.4, $PSNativeCommandUseErrorActionPreference is set to $true by default.

However, after upgrading to 7.4, doing `$PSNativeCommandUseErrorActionPreference` gives me `$false`.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.3#psnativecommanderroractionpreference

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/experimental-features.md

### Author

sdwheeler

### Document Id

976ee643-597a-6c5e-bee4-bb0b72fe3c5f

**Comment by RPitt** [comment]
Hi @michaeltlombardi I think you've missed the point raised by @anthonyvdotbe 

Under 7.4-preview the default value was $true
**However for 7.4 GA the default value is $false** (otherwise it would be a massive breaking change)

The experimental features pages needs better reworking to explain that.

This preference variables defaults below also need updating as they are wrong also.
- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.4  
  == https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
