### ISSUE TITLE
Please learn about encodings, before writing about them

### ISSUE THREAD

**Issue by PoulBak** [MicrosoftDocs/PowerShell-Docs#10681]
### Type of issue

Other (describe below)

### Feedback

Quote from the page:
"In Windows PowerShell, the default encoding is usually Windows-1252, an extension of [latin-1](https://wikipedia.org/wiki/ISO/IEC_8859-1), also known as ISO 8859-1."

Windows-1252 is NOT the same as ISO 8859-1. In particular the three danish characters 'æøåÆØÅ' have different values. Visual Studio gets this wrong in the output, when it thinks it's ISO 8859-1 but it actually is Windows-1252.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/understanding-file-encoding?view=powershell-7.3&source=docs

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/dev-cross-plat/vscode/understanding-file-encoding.md

### Author

@sdwheeler

### Document Id

ba6a0584-4934-989e-3dcc-a6f3571a337f

**Comment by mklement0** [comment]
@PoulBak, while I agree that Windows-1252 is only _largely_ the same as ISO-8859-1, I don't think your claim about these specific characters is correct:

```powershell
 [System.Text.Encoding]::GetEncoding('iso-8859-1').GetBytes('æøåÆØÅ')
'---'
 [System.Text.Encoding]::GetEncoding('windows-1252').GetBytes('æøåÆØÅ')
```

Output, showing that the both encodings results in the same sequence of bytes:

```none
230
248
229
198
216
197
---
230
248
229
198
216
197
```

On a meta note (I'm speaking in no official capacity whatsoever, I'm just a fellow user): The way you've framed your issue is needlessly cantankerous.

---

The short of it is that ISO-8859-1 is largely identical to Windows-1252, except that it is missing the latter's characters in the 0x80 - 0x9F code-point range, which notably includes the `€` symbol.

The complete set of missing characters is:

```none
€ ‚ ƒ „ … † ‡ ˆ ‰ Š ‹ Œ Ž ‘ ’ “ ” • – — ˜ ™ š › œ ž Ÿ
```
