### ISSUE TITLE
function HelloWord misspelled in ISE screenshot

### ISSUE THREAD

**Issue by gschwendt** [MicrosoftDocs/PowerShell-Docs#10750]
### Type of issue

Typo

### Feedback

In the screenshot from PowerShell ISE, the function name is listed as "HelloWord" instead of "HelloWorld".

![full-ise-window](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/25912260/ec4fcc7a-05a5-4007-a53b-c1127a38ba48)

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/exploring-the-windows-powershell-ise?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/windows-powershell/ise/Exploring-the-Windows-PowerShell-ISE.md

### Author

@sdwheeler

### Document Id

c9512d37-ac40-d9e2-91f1-22b4a32f9c0b

**Comment by sdwheeler** [comment]
@gschwendt Thanks for the feedback. It is an unfortunate typo but it is not an invalid name. They function runs by that name in the example screenshot. So the purpose of the example is still valid. The function name could have been `foo` and it would still be a valid example. 

Since the ISE is no longer being being developed and VS Code is the recommended replacement, updating these screenshots is not a priority.
