### ISSUE TITLE
select-object -ExpandProperty string arrayr data issue

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/PowerShell-Docs#10790]
### Type of issue

Missing information

### Feedback

The simplest way of describing the need for further documentation of `-ExpandProperty` and string array data  is with a small useful script 

```
$FormatEnumerationLimit = -1;
$aa = Get-ADComputer -Filter { ServicePrincipalName -ne "$null"} -Properties ServicePrincipalName
   $aa | Select-Object -Property SamAccountName -ExpandProperty ServicePrincipalName |
     Export-CSV -NoTypeInformation -delimiter ';' C:\Temp\server_spn.csv;
```
The image shows part of  `Get-Member` produces from the `Select-Object` statement.

![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/82510602/66071077-bb65-4647-aeb2-86108e36087a)

I see three issues with this that should perhaps be documented. 1. `ServicePrincipalName` is not a named property. 2. `chars` is not a Property. 3. The length of the `Chars` property is a property.

The `Export-CSV` function works fine and will output SamAccountName and Length. It appears that `ParameterizedProperty` is not a Property it knows about.

The real conclusion is that `Select-Object` is broken. Export-CSV is only slightly broken since it does not know about `ParameterizedProperty` .

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-object?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md

### Author

@sdwheeler

### Document Id

fd4684a2-68ac-cb7d-5628-83cbc1bf7a50

**Comment by michaeltlombardi** [comment]
Hi, @Tarjei-stavanger!

Reading through your issue, I think there's a few misunderstandings that I can clear up. In short, when you use both the **Property** and **ExpandProperty** parameters with `Select-Object`, you get the _value_ of the property specified with the **ExpandProperty** parameter. The cmdlet adds a note property for each of the names you specify for the **Property** parameter. This behavior is documented in the reference for the [ExpandProperty][01] parameter.

In your case, this means that your `Select-Object` statement is returning a string value for the **ServicePrincipalName** and adding the value of the **SamAccountName** property to that string as a note property. When you try to serialize that object to a CSV, you get unexpected results instead of the two properties you're expecting.

The rest of this comment shows examples detailing the differences in behavior.

First, given a folder with a few files in it:

```powershell
Get-ChildItem
```
```console
    Directory: C:\code\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           1/11/2024 10:58 AM              0 bar.txt
-a---           1/11/2024 10:58 AM              0 baz.txt
-a---           1/11/2024 10:58 AM              0 foo.txt
```

We can use `Get-Member` to see the available properties of those files:

```powershell
Get-ChildItem | Get-Member -MemberType Properties
```

```console
   TypeName: System.IO.FileInfo

Name                MemberType     Definition
----                ----------     ----------
Target              AliasProperty  Target = LinkTarget
LinkType            CodeProperty   System.String LinkType{get=GetLinkType;}
Mode                CodeProperty   System.String Mode{get=Mode;}
ModeWithoutHardLink CodeProperty   System.String ModeWithoutHardLink{get=ModeWithoutHardLink;}
ResolvedTarget      CodeProperty   System.String ResolvedTarget{get=ResolvedTarget;}
PSChildName         NoteProperty   string PSChildName=bar.txt
PSDrive             NoteProperty   PSDriveInfo PSDrive=C
PSIsContainer       NoteProperty   bool PSIsContainer=False
PSParentPath        NoteProperty   string PSParentPath=Microsoft.PowerShell.Core\FileSystem::C:\code\temp
PSPath              NoteProperty   string PSPath=Microsoft.PowerShell.Core\FileSystem::C:\code\temp\bar.txt
PSProvider          NoteProperty   ProviderInfo PSProvider=Microsoft.PowerShell.Core\FileSystem
Attributes          Property       System.IO.FileAttributes Attributes {get;set;}
CreationTime        Property       datetime CreationTime {get;set;}
CreationTimeUtc     Property       datetime CreationTimeUtc {get;set;}
Directory           Property       System.IO.DirectoryInfo Directory {get;}
DirectoryName       Property       string DirectoryName {get;}
Exists              Property       bool Exists {get;}
Extension           Property       string Extension {get;}
FullName            Property       string FullName {get;}
IsReadOnly          Property       bool IsReadOnly {get;set;}
LastAccessTime      Property       datetime LastAccessTime {get;set;}
LastAccessTimeUtc   Property       datetime LastAccessTimeUtc {get;set;}
LastWriteTime       Property       datetime LastWriteTime {get;set;}
LastWriteTimeUtc    Property       datetime LastWriteTimeUtc {get;set;}
Length              Property       long Length {get;}
LinkTarget          Property       string LinkTarget {get;}
Name                Property       string Name {get;}
UnixFileMode        Property       System.IO.UnixFileMode UnixFileMode {get;set;}
BaseName            ScriptProperty System.Object BaseName {get=if ($this.Extension.Length -gt 0){$this.Name.…
VersionInfo         ScriptProperty System.Object VersionInfo {get=[System.Diagnostics.FileVersionInfo]::GetV…
```

</details>

Compare the different outputs for the following commands:
```powershell
$Properties = Get-ChildItem | Select-Object -Property LastWriteTime, Name
$Properties

$Expanded = Get-ChildItem | Select-Object -Property LastWriteTime -ExpandProperty Name
$Expanded
```
```console
LastWriteTime         Name
-------------         ----
1/11/2024 10:58:04 AM bar.txt
1/11/2024 10:58:07 AM baz.txt
1/11/2024 10:58:01 AM foo.txt

bar.txt
baz.txt
foo.txt
```
Now, when we use `Get-Member` on the output from `Select-Object`, we can see another difference:
```powershell
$Properties | Get-Member -MemberType Properties

$Expanded | Get-Member -MemberType Properties
```
```console
   TypeName: Selected.System.IO.FileInfo

Name          MemberType   Definition
----          ----------   ----------
LastWriteTime NoteProperty datetime LastWriteTime=1/11/2024 10:58:04 AM
Name          NoteProperty string Name=bar.txt

   TypeName: System.String

Name          MemberType   Definition
----          ----------   ----------
LastWriteTime NoteProperty datetime LastWriteTime=1/11/2024 10:58:04 AM
Length        Property     int Length {get;}
```
Notice that the types are different. When you use the **ExpandProperty** parameter, the `Select-Object` cmdlet returns the actual value for that property on the input object, as [documented in the parameter reference][01].

When you used the `Select-Object -Property SamAccountName -ExpandProperty ServicePrincipalName` command, you returned the value of the **ServicePrincipalName** property with the **SamAccountName** property added to the output object as a **NoteProperty**.

If you want to select both properties and only those properties, you would want to run this command instead:

```powershell
$aa | Select-Object -Property SamAccountName, ServicePrincipalName
```

You can see the same behavior if we export the differently selected data from before:

```powershell
$Properties | Export-Csv -NoTypeInformation properties.csv
Get-Content properties.csv
```
```csv
"LastWriteTime","Name"
"1/11/2024 10:58:04 AM","bar.txt"
"1/11/2024 10:58:07 AM","baz.txt"
"1/11/2024 10:58:01 AM","foo.txt"
```

The output from `Select-Object` using only the **Property** parameter writes a CSV as expected, with both the **LastWriteTime** and **Name** property values for each object.

```powershell
$Expanded | Export-Csv -NoTypeInformation expanded.csv
Get-Content expanded.csv
```
```csv
"LastWriteTime","Length"
"1/11/2024 10:58:04 AM","7"
"1/11/2024 10:58:07 AM","7"
"1/11/2024 10:58:01 AM","7"
```

The output from `Select-Object` using both the **Property** and **ExpandProperty** parameters writes an unexpected CSV, containing the value of the string value's **Length** property and **LastWriteTime** note property added to the output by the cmdlet.

The issue you're seeing in the unexpected output is the same as demonstrated in this example. When you want an object with both properties, you want to use only the **Property** parameter, not the **ExpandProperty** parameter.

Finally, to address your question around the **Chars** parameterized property, it's not included in the CSV because that property requires specific input to return a value. Note that the property is returned when you call `Get-Member` without specifying a value for the **MemberType** property, but not when you call `Get-Member -MemberType Properties`.

As an example, consider the following snippet and output:

```powershell
$Expanded[0]
$Expanded[0].Chars(0)
$Expanded[0].Chars
$Expanded[0].Chars()
```
```console
bar.txt

b

IsSettable          : False
IsGettable          : True
OverloadDefinitions : {char Chars(int index) {get;}}
TypeNameOfValue     : System.Char
MemberType          : ParameterizedProperty
Value               : char Chars(int index) {get;}
Name                : Chars
IsInstance          : True

GetValueInvocationException: Cannot find an overload for "Chars" and the argument count: "0".
```

A parameterized property is similar to a method, and because it requires specific input, it doesn't serialize when using the `Export-Csv` cmdlet.

[01]: https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/select-object#-expandproperty
