### ISSUE TITLE
Example 10, -AsUTC output is wrong

### ISSUE THREAD

**Issue by gummigroda** [MicrosoftDocs/PowerShell-Docs#10842]
### Type of issue

Code doesn't work

### Feedback

Running `Get-Date -Date "2020-01-01T00:00:00" -AsUTC` should output something like `Tuesday, 31 December 2019 16:00:00` not as the article states: 
![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/15022172/44a3e537-cbe7-4069-9de6-82cdc23f7a72)

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Utility/Get-Date.md

### Author

@sdwheeler

### Document Id

377b439a-f6e4-f741-e3b5-502861fa1c20

**Comment by sdwheeler** [comment]
Since the input string does not include a time zone offset, it depends on what time zone your system is set to. Without the time zone offset, the datetime of the string is interpreted as being a local time. Example 10 shows the time zone as UTC-08:00. Therefore, the output is 8 hours ahead of the input value. If you include a time zone offset in the input, then conversion to UTC is based on that offset.

For example:

```
PS> Get-Date -Date "2020-01-01T00:00:00+2:00" -AsUTC

Tuesday, December 31, 2019 10:00:00 PM
```

If you want the output to be formatted differently, use the one of the formatting parameters:

```
PS> Get-Date -Date "2020-01-01T00:00:00+2:00" -AsUTC -UFormat '%F %T'

2019-12-31 22:00:00
```
