### ISSUE TITLE
Provide way to "View page source".

### ISSUE THREAD

**Issue by RokeJulianLockhart** [MicrosoftDocs/PowerShell-Docs#11023]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.4

### Summary

Add a "View page source" URI in the footer of every document, like https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.host.ihostuisupportsmultiplechoiceselection?view=powershellsdk-7.4.0#definition does: https://docs.gitlab.com/ee/#:~:text=Contact-,view%20page%20source,--%0AEdit%20in%20Web should demonstrate the feature.

### Details

For instance, I've been utterly unable to locate the source code for https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.host.ihostuisupportsmultiplechoiceselection?view=powershellsdk-7.4.0#definition.

I tried to locate a meta https://github.com/orgs/MicrosoftDocs/repositories?type=source to file this in, but of the 200 I checked, all were for product-specific documentation, so I just chose the one which I was most familiar with to file this at instead.

**Comment by sdwheeler** [comment]
There is an edit button at the top of each page that takes you to the source of that page in GitHub.

![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/19415881/74a50c6f-1807-4a2f-80e1-6e7ac820e8f6)

If the edit button is not there, then the source is not publicly available. That is by design.

In your example, you are linking to .NET API reference. That content is not editable because it is autogenerated from ///-comments in the source code. You have to look in the source repository. See https://github.com/PowerShell/PowerShell/blob/d370d7d586b15618ebe3ee2451c1838e1b4ba6e7/src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs#L1344

**Comment by RokeJulianLockhart** [comment]
> https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11023#issuecomment-2059209301

Thank you, @sdwheeler. That is comprehensive.
