### ISSUE TITLE
date keyword (or is it something else)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/PowerShell-Docs#11050]
### Type of issue

Other (describe below)

### Feedback

This is not an issue, but I can't think of a better place to ask.  I stumbled upon this command:

```powershell
date
```
It seems to be exactly the same as either Get-Date or [datetime]::Now

But I don't find it with Get-Alias, nor Get-Command.  Next thing I thought, is it a keyword?  But I don't see it listed here.  Wondering if anyone knows what it is, and if there are any other special commands like this which I might be able to find once I find the source of "date".

Thanks in advance.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_keywords?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Keywords.md

### Author

@sdwheeler

### Document Id

3654cb3a-e931-f658-1c87-8814a947d016

**Comment by sdwheeler** [comment]
`Date` is not a keyword. When you enter a command at the prompt, PowerShell has to resolve the source of the command. If you don't specify a path, PowerShell uses the following precedence order when it runs commands.

1. Alias
2. Function
3. Cmdlet
4. External executable files (including PowerShell script files)

If it can't find the command, it adds `Get-` to the name. So `Date` becomes `Get-Date`. This will work for any `Get-` command where the noun does not resolve to another command or a language keyword. For example, this won't work for `Get-Process` because `process` is a language keyword.

See Mike's blog post for more information. https://mikefrobbins.com/2017/09/27/not-specifying-a-verb-in-powershell-is-an-expensive-shortcut/
