### ISSUE TITLE
Create topic for side-by-side zip-based installs

### ISSUE THREAD

**Issue by nitinbps** [MicrosoftDocs/PowerShell-Docs#1334]
PS 6.0 ignores Group Policy script execution settings if the module is under PSHOME. There should a guideline to users on how and where to install PS 6.0 such that Group Policy settings can be enforced by installing PS into a secure location where non-admins can't install any module.

**Comment by SteveL-MSFT** [comment]
@juanpablojofre since this is more of an about topic, I'm assigning to you.  For now, we should document for PSCore6 (not applicable to downlevel as they are in secured locations) that the script execution policy doesn't apply to scripts/modules in $PSHOME as they are implicitly trusted.  For v5.1 and below, this is fine as Windows PowerShell resides in System32.  However, for PSCore6 the user should ensure they install it to a secure location.  If using the MSI, we install to ProgramFiles which is considered secure as non-admins cannot write to that location, however, PSCore6 allows for xcopy deploy to any file location so it's possible for someone else to put malicious code (or even overwrite powershell.exe) if the ACL on that folder isn't secure.

cc @LeeHolmes

**Comment by juanpablojofre** [comment]
@SteveL-MSFT, got it!!

**Comment by sdwheeler** [comment]
@SteveL-MSFT Has the install story changed? What is the recommendation for a secure installation? Also, do we have guidance for ACLs on the install location for non-Windows?

**Comment by SteveL-MSFT** [comment]
@sdwheeler install story has not changed.  Keep in mind that there are two types of installs: using one of our packages which installs it to the system and using zip/tgz which any non-admin can use and no installer gets run.  For non-Windows using one of our packages which requires `sudo` to install, it is ACLd the same as any other similar package.  Is there something specific you are asking?

**Comment by sdwheeler** [comment]
@SteveL-MSFT The core intent of this issue is to documenthow and where to install PS 6.0 such that Group Policy settings can be enforced by installing PS into a secure location where non-admins can't install any module.

I am looking for that guidance for both Windows and non-Windows installs. I have no experience with non-Windows installs to this may not be an issue. But we need to provide guidance for Windows.

**Comment by SteveL-MSFT** [comment]
Group Policy doesn't apply to non-Windows.  For Windows, guidance is to install using our signed .msi installer which will put it in ProgramFiles where only TrustedInstaller has write access by default.

**Comment by sdwheeler** [comment]
I know that Group Policy does not apply to non-Windows. But it is a question of ACLs to provide sufficient protection on the install location on non-Windows systems. If sudo manages that, then there is no issue.

**Comment by SteveL-MSFT** [comment]
@sdwheeler our Unix packages requires sudo to install.  the installed folder only has write access to root and everyone else has read and execute permissions.

**Comment by sdwheeler** [comment]
@nitinbps V6 has released. It installs on Windows using an MSI package. Is this still an issue?

**Comment by SteveL-MSFT** [comment]
@sdwheeler installing using the MSI should be ok as it should be ACLd correctly in $env:programfiles, however, if using the zip pkg we still have the issue.  Basically, I think what needs to be documented is that scripts/modules in $PSHOME are implicitly trusted.

**Comment by sdwheeler** [comment]
@joeyaiello Need to discuss the security implications of zip-based install vs. MSI install

**Comment by sdwheeler** [comment]
Setup docs have been updated.
