### ISSUE TITLE
Clean up YAML blocks for parameters in all cmdlet reference

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#2179]
There are many cases across all of the documentation where information about wildcard support, position number, default values, etc. on the parameters is incorrect. So far we have been correcting these one at a time. We need an automated way to scan the released modules and update the docs accordingly.

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by zjalexander** [comment]
see also: #1672, #1258, #1109

**Comment by sdwheeler** [comment]
Does PlatyPS help us here? PlatyPS generates the stub markdown files. We could regenerate them and merge the diffs?

**Comment by SteveL-MSFT** [comment]
@sdwheeler the good news is that PlatyPS has a `Update-MarkdownHelp` cmdlet that updates the YAML of the parameters and the syntax.  However, after running it, I notice that the Position property starts at index 1 instead of 0 which is currently used in the docs.  It seems that 1 is more accurate for human consumption.  Will have to fix this as a series of PRs as just updating the PSCore6 ref docs resulted in 263 changed files.  If you agree to the indexing, I'll review the changes and submit a PR.

**Comment by sdwheeler** [comment]
YAML blocks have been manually updated. Work is ongoing to improve PlatyPS.
