### ISSUE TITLE
Need documentation on how to use PowerShell.SDK

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#2967]
Users are hitting problems using the SDK.  See https://github.com/PowerShell/PowerShell/issues/7886#issuecomment-425953301

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [X] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by iSazonov** [comment]
I'd suggest to create Wiki and ping community (and MVPs) to share their experiences.

**Comment by doctordns** [comment]
A wiki is a great idea. All you need is one or two passionate writers to create and keep it fresh and up to date. This is, however, far easier in theory than in principal. In my experience, unless there is some underlying motivation (ie your job depends on it), wiki maintainers come and go. I hate to throw water on the fire of an idea, but almost every community project goes the way of the dodo unless there is a huge base. So PS Gallery isn't going away, docs.microsoft.com are not going away - but I'd bet dollars for donuts that you'll find sustaining an SDK wiki a challenge.

I really hope I am wrong. Go out and create one, document it in docs.microsoft.com and see where it goes. 

Personally, rather than creating a wiki, I'd prefer to see any 'how to use sdk' pages be here in docs.microsoft.com where there is a higher hope for content longevity.

**Comment by kilasuit** [comment]
There is already existing SDK Documents at https://docs.microsoft.com/en-us/powershell/developer/windows-powershell

Though these site on a site that bares a banner showing it's no longer being updated as per this first link that points to installing the SDK https://msdn.microsoft.com/en-us/library/ff458115.aspx

Can these docs be moved into the main PowerShell Doc's repos and then be appropriately updated to include SDK details for PowerShell 5 / 5.1 and 6 ?

**Comment by SteveL-MSFT** [comment]
@sdwheeler does it make sense to move the old SDK docs?

**Comment by sdwheeler** [comment]
@SteveL-MSFT Let's talk about this in Shiproom

**Comment by sdwheeler** [comment]
@SteveL-MSFT SDK docs can be found at https://github.com/PowerShell/PowerShell-Docs/tree/staging/developer. We need to update the existing docs. Moving the SDK docs into the main TOC is part of a bigger reorganization project.

**Comment by sdwheeler** [comment]
Status update - SDK docs have been moved in to main docset. There are some new articles about developing cross-platform modules. I am closing this issues as complete. We still need more documentation for examples using the SDK but we need more specific issues.
