### ISSUE TITLE
Docs needed for 'Conversions from PSMethod to Delegate'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3068]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5287

**Comment by joeyaiello** [comment]
Not sure where this should be doc'd. Thoughts?

**Comment by sdwheeler** [comment]
This seems like more of an SDK change. What is the difference in behavior that the user sees? That is what we need to document.

**Comment by SteveL-MSFT** [comment]
Basically what is enabled by this is a new language feature.  You can pass a PSMethod (like defined in a PS class) to a .NET method that accepts a delegate (function) as the conversion happens automatically for you.  In the example at the top of the PR, the line `[M]::AggregateString((gci).Name, [M]::DoubleStrLen)` would fail in Windows PowerShell because `[M]::DoubleStrLen` is a PSMethod and the `[M]::AggregateString()` expects a func (delegate).  I don't know where we would document this.

**Comment by sdwheeler** [comment]
Looks like this shipped in v6.2.1
