### ISSUE TITLE
Docs needed for 'Member enumeration works with setter methods, but not with property assignments'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3070]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/5271

**Comment by joeyaiello** [comment]
I'm not sure *where* this should be documented. Any ideas?

**Comment by joeyaiello** [comment]
I'm not sure *where* this should be documented. Any ideas?

**Comment by sdwheeler** [comment]
Notes copied from https://github.com/PowerShell/PowerShell/issues/5271
---

You can use member enumeration to _get_ property values from all members of a collection, but you cannot currently _set_ them (to a given, single value).
By contrast, you _can_ use a setter _method_ to do so.

```powershell
# Create 2 temporary files and collect their [System.IO.FileInfo] representations
# in an array.
$files = (New-Item -Type File -Force '/tmp/t1.txt'), (New-Item -Force -Type File '/tmp/t2.txt')

# Using member enumeration, try to set a property on all elements of the array
# to the same value:

# Try to to *assign to a property*.
# !! FAILS with error "The property 'LastWriteTime' cannot be found on this object."
$files.LastWriteTime = (Get-Date).AddDays(-1)     

# Try the property's *setter method* - this works.
$files.set_LastWriteTime((Get-Date).AddDays(-1))

# Verify that the date was set to yesterday.
$files
```

(Note that `NoteProperty` members, such as found on `[pscustomobject]` instances, do not have setter methods.)

If there are good reasons not to allow that, I suggest making the error message less confusing (if `$someColl.foo` finds property `foo` on the collection members, then `$someColl.foo = ...` should indicate that assignment is disallowed rather than claiming that the property doesn't exist).
---

NOTE: you can call _any_ method with member enumeration, and there again you may get tripped up by not realizing that the method may be called on _each member_ - and thus do unintended things.

Take the following example:

```powershell
> $a = 1, 2; $a.Reset()
Method invocation failed because [System.Int32] does not contain a method named 'Reset'
...
```

Say you thought that arrays have a `.Reset()` method and you wanted to call it on the whole array, but since they don't, `.Reset()` is called on _each array element_. No harm done in this case, because the `[int]` elements happen to have no `.Reset()` method, but they certainly _could_.

(Of course, you could now make the case that calling methods should be disallowed too, but note that that would be a breaking change.)

**Comment by sdwheeler** [comment]
I am thinking this could be part of a Deep Dive article on collection enumeration.
