### ISSUE TITLE
Docs needed for 'Why is [pscustomobject] the same as [psobject], even though a distinct [System.Management.Automation.PSCustomObject] type exists?'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3092]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/4344

**Comment by joeyaiello** [comment]
Not sure if this should go straight into [PSCustomObject](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.pscustomobject?view=pscore-6.0.0) or [PSObject](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psobject?view=pscore-6.0.0) docs, or if we need an `about_PSCustomObject` topic.

**Comment by sdwheeler** [comment]
@MicrosoftDocs/shiproom-psdocs We need to discuss the need for this documentation.

**Comment by theJasonHelmick** [comment]
Not sure that we need documentation on this, but I would like to get @JamesWTruher to explain the differences to @sdwheeler and I so we can decide on Docs.  I'll comment here after I've spoken to Jim.

**Comment by sdwheeler** [comment]
Some notes

- psobject - IFormattable, IComparable, ISerialized, IDynamicMetaObjectProvider
- pscustomobject  – IDynamicMetaObjectProvider

Both type accelerators are mapped to the same class:

```
PS> [pscustomobject]

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     PSObject                                 System.Object

PS> [psobject]

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     PSObject                                 System.Object
```

The `[pscustomobject]` type accelerator was added in PowerShell 4.0 with extra syntactic sugar. There was a common pattern of creating new objects using `New-Object` and `Add-Member` to add properties. Casting a hashtable to `[pscustomobject]` achieves the same result.

`[pscustomobject]` is not a _true_ type, meaning that you can use it for type coercion or type comparison.

```
# Even though their names strongly suggest identity, they are different types.
> [pscustomobject] -eq [System.Management.Automation.PSCustomObject]
False

# Any object returned by a *command* (as opposed to an expression)
# returns $True for -is [psobject], and therefore also [pscustomobject]
# since both are mapped to PSObject
> (Get-Item /) -is [pscustomobject]
True

# Casting anything other than a hashtable literal to [psobject] is a no-op, 
# and therefore also with [pscustomobject]
> ([pscustomobject] 666).GetType().Name
Int32
```

Also, since casting to `[psobject]` does not have the syntactic sugar, you get different results.

```
PS> ([PSCustomObject]@{Property = 'Value'}).GetType().FullName
System.Management.Automation.PSCustomObject

PS> ([PSObject]@{Property = 'Value'}).GetType().FullName
System.Collections.Hashtable
```
