### ISSUE TITLE
Docs needed for ' Fix Select-Object to approve UX and fix return a property named *'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3113]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/2421

**Comment by joeyaiello** [comment]
https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Select-Object?view=powershell-6

**Comment by sdwheeler** [comment]
This change fixes two bugs:
1. Pre v6 - When `-ExcludeProperty` is used `Select-Object` returns all properties included the excluded property if `-Property *` is not also used. In v6+, `-Property *` is assumed if not supplied.
2. Pre v6, `-Property *` could add a property named `*` to the output object. This is fixed in v6+.
