### ISSUE TITLE
about_using doesn't mention "using assembly" syntax

### ISSUE THREAD

**Issue by djohnst10** [MicrosoftDocs/PowerShell-Docs#3277]
The about_using help topic doesn't mention the "using assembly &lt;assembly name&gt;" syntax.

Is that syntax not supported for PowerShell 6?

If it is, where would PowerShell search for and load assemblies from?

If it is not, then the documentation should note that the "using assembly" syntax is not supported in PowerShell 6, although it is supported in PowerShell 5 and PowerShell 5.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee0c5b0-8465-adcc-be1b-9e6aafa4199d
* Version Independent ID: bc27ba48-5641-d363-7fc4-06ea01efa9e2
* Content: [about_Using](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_using?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/About_Using.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/About_Using.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by HarinezumiSama** [comment]
**NOTE**: In PS 6.2, `using assembly` seems to work only when a full path to an assembly file is specified.

**Comment by jszabo98** [comment]
Works ok in 5.1.

```powershell
using assembly System.Windows.Forms
using namespace System.Windows.Forms
[messagebox]::show('hello world')
```

**Comment by rjmholt** [comment]
Ah, I see @joeyaiello already tagged me and I never got around to writing anything here.

There's some good discussion of this in:
- https://github.com/PowerShell/PowerShell/issues/9929
- https://github.com/PowerShell/PowerShell/issues/3641
- https://github.com/PowerShell/PowerShell/issues/2074
- https://github.com/PowerShell/PowerShell/issues/6653

Some particular points:

- `using assembly` was intended for type resolution in PowerShell classes (i.e. when the `class` keyword is used); it resolves types at parse-time before the parser tries to determine if types exist to create the type for PowerShell classes. If you're not using a PowerShell class, you're better off using `Add-Type`
- PowerShell parsing is supposed to be "safe"; you should be able to parse any PowerShell script no matter how malicious and not have it execute code somehow. If such a script contains a class and the class depends on an assembly, we need to be able to examine that assembly without it being able to execute code. In .NET Framework (PowerShell 5.1 and below), you could use the [reflection-only assembly load context](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-load-assemblies-into-the-reflection-only-context) to do this, guaranteeing that no code from it will execute. .NET Core removed this and it's a lot of work to work around.
- However (perversely), if the parse succeeds, `using assembly` will load an assembly it's pointed to
- But, since PowerShell 6+, `using assembly` won't work with a partial name. Presumably this was a choice made when the initial move to .NET Core was made, since there's no GAC in .NET Core. But since then, other assembly resolution methods in PowerShell look in `$PSHome` and, on Windows, in the GAC.

So essentially `using assembly` is valid syntax and it does something, but it really doesn't improve on `Add-Type` yet. Even if you're defining classes in PowerShell, it still doesn't do the thing it was intended to do, and the workaround that's gained traction there is something like this:

main.ps1:
```powershell
Add-Type -Path ./myasm.dll
. ./classes.ps1
```

classes.ps1:
```
class MyPSClass : MyAsmClass
{
}
```
