### ISSUE TITLE
Missing command alias reference

### ISSUE THREAD

**Issue by wesinator** [MicrosoftDocs/PowerShell-Docs#3662]
Alias `iex` is not mentioned here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d669d38f-7692-bbaa-2c88-ba1b1d2bb4c1
* Version Independent ID: 9d592d60-e29c-84e6-2e43-078e2a69fb97
* Content: [Invoke-Expression (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-expression?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
None of the reference article mention the cmdlet alias. They only mention the parameter aliases. This is by design in our current documentation system. The alias can be different across platform. For example on Windows, PowerShell created the alias `ls` for `Get-ChildItem`. But that does not exist on non-Windows platforms.

You can find a list of aliases for a cmdlet following this example:

```
PS D:\> Get-Alias -Definition Get-ChildItem

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           dir -> Get-ChildItem
Alias           gci -> Get-ChildItem
Alias           ls -> Get-ChildItem
```
