### ISSUE TITLE
Looking for missing parameters

### ISSUE THREAD

**Issue by danielkr71** [MicrosoftDocs/PowerShell-Docs#3675]
test-connecion -computername xyz count=1 | fl -property *  shows me a parameter "timestamprecord" which is blank.  How can I use this parameter?  I'm looking for timestamped results and have to script it, but output of all result properties looks like I shouldn't have to.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e7924d2-dbe7-af64-94de-dc0a2d87a91f
* Version Independent ID: 1cf2ccd2-f099-3f92-b698-36311baa0b81
* Content: [Test-Connection (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Test-Connection?view=powershell-3.0)
* Content Source: [reference/3.0/Microsoft.PowerShell.Management/Test-Connection.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Test-Connection.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
In PS 5.1 and older, `Test-Connection` returns a WMI **Win32_PingStatus** object. The **TimeStampRecord** property you reference is part of that class. However, the `Test-Connection` cmdlet does not have the ability to request timestamps so that property never gets populated.

In PS v6, the cmdlet return **System.Net.NetworkInformation.PingReply** objects. These are much simpler objects and do not contain the timestamp info. Also, the v6 cmdlet does not have a way to request timestamps.
