### ISSUE TITLE
Bad discoverability of most essential PowerShell documentation

### ISSUE THREAD

**Issue by NorbertNemec** [MicrosoftDocs/PowerShell-Docs#3744]
I just discovered this page:
  PowerShell 6 / Reference / Microsoft.PowerShell.Core / About
This is the last place where I would look for the most essential language definition of PowerShell. Even in search engines it shows up in a weird, un-official way. I often wondered why the PowerShell language was so badly documented and just heard from a colleague that he had the same problem. This content should be placed in a very prominent location "Language Reference" or similar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8875da6a-cf61-bd6b-443d-e938f6912786
* Version Independent ID: 10376fbc-664d-e09d-d6ca-9a4a610dedba
* Content: [About](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/About.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/About.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by matt9ucci** [comment]
The "About_*" help topic is what we call "Conceptual Help". It is [a type of module help](https://docs.microsoft.com/en-us/powershell/developer/module/writing-help-for-windows-powershell-modules#types-of-module-help). That's why they are placed under Microsoft.PowerShell.Core, I think. (I agree to the "bad discoverability" :sweat_smile:)

**Comment by NorbertNemec** [comment]
Hi Matt,

thanks for the explanation. I can understand the technical reasoning, but I fear that this is seriously harming the immense value of these pages:


  *   from an external point of view, the “About_” prefix appears confusing. My first association is “About screen” and in technical documentation, I have often seen this term used for a similarly small prolog section giving minimal background about the project. I would never expect anything substantial behind that term.
  *   the flat, alphabetical list of articles is not helpful at all. I have read documentation for many different programming languages. Each of them has exactly this kind of content at its core, but it is always well structured in layers of complexity, e.g. “syntax”, “types”, “expressions”, “statements”, “functions”, “classes”, … (depending on the specifics of the language) – Now just imagine a book about C++ structured alphabetically by keywords…
  *   It may be technically correct to place these under Microsoft.PowerShell.Core, but for content of this importance, the main focus should be the external perspective: how is the content found, what does it look like in a browser, how does it show up in search engines?

Sorry to be so strong in making these points, but I have only recently started to dig into PowerShell and realized the value that is hidden in it. I started batch scripting on MS-DOS, then moved deeply into Linux for a long time, returned to Windows a few years ago and always found PowerShell weird and badly documented with most of my google searches about PowerShell leading to confused forum discussions. Only over the past weeks I started to realize that it is actually a really well-designed programming language that I should have taken seriously much earlier…

Greetings,
Norbert

**Comment by doctordns** [comment]
```about_*``` is a well understood term with respect to PowerShell help and conceptual help. It was an important investment (both help in general and conceptual help) in V1. June Blender and company did an outstanding job bringing the concepts of this new scripting parigigm to life. That effort has continued,and today there is good practical advice on how to create that help for your modules.  Also, that 'flat alphabetical list' is excelent for discovery using wild cards and/or regular expressions.

I believe the topics _are_ correctly placed since they are delivered by the Microsoft.PowerShell.Core module. 

But that is not to sympthasise with your concerns over search engines. The algorithms over at bingle just need tuning! In the move from technet/msdn.microsoft.com to docs.microsoft.com it took a good 6-9 months before Google started sending me to docs.microsoft.com. 

An important thing to remember, with respect to PowerShell nothing is by accident. Every feature you see has been thought through carefully. Yes some times chouices have to be made - after all to ship is to choose as the wise man once said. But you need to understand those features. About_ is one I think to be incredible.

**Comment by sdwheeler** [comment]
@NorbertNemec We are actually working on ways to restructure the online help to make those articles more discoverable. But this is no small task. As @doctordns mentioned, the `about_*` topics have been in PowerShell since the beginning. You can easily find these topics using `Get-Help about_*`.

**Comment by NorbertNemec** [comment]
Hi Thomas,

thanks for the clarification and sorry again for my strong words. I guess that was due to my surprise of finding this documentation and the sadness of not having discovered the beauty of PowerShell much earlier…

I am sure there is lots of thought behind each detail, otherwise PowerShell would not have reached the quality I am discovering just now. I can only express my personal perspective as a programming language connoisseur who is used to read documentation in the browser or as PDF or google the most obvious terms. And from that perspective the beauty of PowerShell has somehow managed to escape my attention for a surprisingly long time. I worked with PowerShell scripts on several occasions, had questions, googled, found the documentation, tutorials, examples and forum discussions but never stumbled over the about pages.

Maybe all it takes is an additional section in the PowerShell documentation that presents PowerShell as a “Language”, referencing the existing pages, similar to:

https://docs.python.org/3/reference/index.html
https://www.lua.org/manual/5.3/
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/index
https://golang.org/ref/spec
https://perldoc.perl.org/index-language.html (really bad example!)

(each found within a few obvious clicks)

Greetings,
Norbert
