### ISSUE TITLE
Push Server

### ISSUE THREAD

**Issue by Mixonic73** [MicrosoftDocs/PowerShell-Docs#3814]
Can you please also include samples for a Push Server configuration and any special WinRM etc. settings that may need to be in place.  It would also be nice to have some real life samples such as (Change Language, TimeZone, NTP) in one configuration file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102d0c2d-c574-5958-ace9-f18542a3b718
* Version Independent ID: 5b93e3b0-cf61-2f27-7786-5f391ef5f78d
* Content: [DSC Pull Service](https://docs.microsoft.com/en-us/powershell/dsc/pull-server/pullserver#feedback)
* Content Source: [dsc/pull-server/pullServer.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/dsc/pull-server/pullServer.md)
* Product: **powershell**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by doctordns** [comment]
A push server just needs to be a host that has an up to date OS on which you have loaded the DSC resources you wish to leverage. The 'push server' can be a Windows 10 system quite easily. There is nothing special to set up. 

The server you push to just has to have an up to date OS with WInRM running. By default, Windows Server 2016 and Windows Server 2019 are set up correctly out of the box to receive a push-DSC configuration.

I am not sure what configuration details would be useful since it for configuring Windows Server, it's all automagic. The DSC resources needed to configure what the OP mentioned are not, IIRC, shipped by default. They would be third-party DSC module and this page is not the place for that - IMHO.

**Comment by fleShpaiNt** [comment]
I appreciate the response, any idea why winrm would work on one host and not the other?

Server A works with localhost
Fails with hostname/IP

Server B works with hostname of Server A or B

??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by doctordns** [comment]
Without knowing more it is hard to say specifically why it does not work for you. But this sounds to be a support issue, not a documentation issue.

**Comment by fleShpaiNt** [comment]
All good, got it fixed.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________
