### ISSUE TITLE
Where are the notes on the effect of this command on non-Windows platforms

### ISSUE THREAD

**Issue by rkeithhill** [MicrosoftDocs/PowerShell-Docs#4005]
That is, it does nothing on non-Windows platforms because execution policy does not apply on non-Windows platforms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff70cc60-7128-d1a8-6fc1-c5a4e7d79a25
* Version Independent ID: 55d48d73-6fc4-29de-4cc1-c02bcb6a13d8
* Content: [Set-ExecutionPolicy (Microsoft.PowerShell.Security)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md)
* Product: **powershell**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by sdwheeler** [comment]
It is documented in about_Executution_Policies but should be added here.

**Comment by Archehandoro** [comment]
Wouldn't it make more sense to have the policy set to "RemoteSigned" rather than unrestricted for non-Windows computers?

For example, without the execution policy set to RemoteSigned it is not possible to change the "HiddenFromExchangeClientsEnabled" flag on the Set-UnifiedGroup cmdlet, which is very helpful given the default behaviour of Teams creation regarding O365 groups setting it to $true.

**Comment by doctordns** [comment]
Opinion is varied on the value of RemoteSigned. It looks nice, but it really is not an effective control. ALL it does is to stop you from running a script you obtained from elsewhere unless it has been signed. LIke I say, it sounds good - but all you have to do is to cut/paste it to a local file and run a LOCAL script. 

There may be environments which might make use of it, but as I see it, about all it does, in practice, is to slow me down. Suppose it's 4 AM and a script blows up. You can fix it, but you can't run it because the signing key is locked in the safe and the guys with the combination are not going to be in for another 4-5 hours. Under such situations, I'd have to ask about the wisdom of the policy.

**Comment by TravisEz13** [comment]
@doctordns Nothing in `remotesigned` or `allsigned`, which prevents you from creating your own cert and signing the file on the local machine, not that this changes the ultimate conclusion.  I think the purpose is to **try** and tell you when you are doing something stupid.
