### ISSUE TITLE
This could be improved with an example

### ISSUE THREAD

**Issue by joshuaalm** [MicrosoftDocs/PowerShell-Docs#4247]
Having used PowerShell to do a few things by now, I understand the concept of Object-based scripting.  However, when I first heard of PowerShell many years ago, I wondered what improvements this brought to scripting that couldn't be handled with the output of regular text-based commands.  For instance, looking at the output of 'Get-Location | Get-Member' vs 'cd' or 'pwd' on *nix, I might have no idea where and how I might ever use the extra properties and methods available.  An example that highlights those justifications for an Object-based scripting language would improve this section.  https://docs.microsoft.com/en-us/powershell/scripting/learn/understanding-important-powershell-concepts?view=powershell-6#output-is-object-based

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4384575-6e45-e6dc-583e-1b77237710bd
* Version Independent ID: eb5a526a-1b4e-9c28-f7ee-f6625191c551
* Content: [Understanding important PowerShell concepts](https://docs.microsoft.com/en-us/powershell/scripting/learn/understanding-important-powershell-concepts?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/learn/Understanding-Important-PowerShell-Concepts.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/Understanding-Important-PowerShell-Concepts.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
You won't always need all of the properties of an object. In fact, you may never need some properties. But the advantage of EVERYTHING being an object is that you have a consistent and predictable way of accessing property values of an object. So there is no arbitrary parsing.

**Comment by OUDcollective** [comment]
I have never been as confused as I am in this moment. 

Im about 20-25 years late to this party, that's granted. 

But you'd think by now there'd be an authority for diving into this digital abyss. Instead of learning and moving forward, I keep finding myself trying out CodePen and Mozilla, then Microsoft, and over to GitHub, then W3Schools, and trying Linkedin Learning or considering UDemy. 

And by then, it's mundane and forty eleven tabs are open. 

And nothing gets done. 

I understand html but really know nothing more than <div> and </div>, but I get it as I do have a blog and publish content. Aside from that, I can't push past this to Git to learning freaking API's and how to utilize that resource. 

Hello... Helloo... Is there anybody out there? 

Lead me to the path that leads to the key,. That opens the door. 

P-L-E-A-S-E

**Comment by OUDcollective** [comment]
See my <div > Disappeared :)

**Comment by OUDcollective** [comment]
Ha! My >Div<

**Comment by sdwheeler** [comment]
@OUDcollective This is not the proper forum for the help you seek.
