### ISSUE TITLE
include examples for -filter

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/PowerShell-Docs#4415]
for example, -filter "*.CSV"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c805a7fd-13a5-6002-dc57-43d97aee00fd
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by jszabo98** [comment]
Also, note that -filter does not support square bracket type wildcards, so not all wildcards.

```powershell
get-childitem -filter [abc]*
```

**Comment by mklement0** [comment]
Good point, @jszabo98 - see https://stackoverflow.com/a/17739503/45375 for what pattern language the filesystem provider's `-Filter` parameter actually supports.

**Comment by joeyaiello** [comment]
@SteveL-MSFT let's talk about this one

**Comment by sdwheeler** [comment]
The filter is passed to the .NET API to enumerate files. That API only supports `*` and `?` wildcards.

**Comment by jszabo98** [comment]
The docs are incorrect then.  There's an 'about_wildcards' link under -filter.

-Filter
Specifies a filter to qualify the Path parameter. The FileSystem provider is the only installed PowerShell provider that supports the use of filters. You can find the syntax for the FileSystem filter language in [about_Wildcards](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-6). Filters are more efficient than other parameters, because the provider applies them when the cmdlet gets the objects rather than having PowerShell filter the objects after they are retrieved.

**Comment by jszabo98** [comment]
Note that -filter also matches against the short 8.3 versions of filenames.

```powershell
PS C:\> cmd /c dir /x
 Volume in drive C has no label.
 Volume Serial Number is F81A-DB00

 Directory of C:\

07/17/2019  02:19 PM    <DIR>                       .
07/17/2019  02:19 PM    <DIR>                       ..
07/17/2019  02:19 PM                10 VERYLO~1.TXT verylongname.txt
               1 File(s)             10 bytes
               2 Dir(s)   4,032,000,000 bytes free

PS C:\> ls -filter *~*


    Directory: C:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        7/17/2019   2:19 PM             10 verylongname.txt
```
