### ISSUE TITLE
PassThru parameter does not function as described per documentation

### ISSUE THREAD

**Issue by weigh2tall** [MicrosoftDocs/PowerShell-Docs#4468]
Running PS Version: 5.1.17763.134.  -PassThru parameter is not respected as described here.  Even with PassThru specified the original objects supplied are wrapped by to include the additional column.  
In same version if I omit the -passthru parameter I DO achieve the desired results

```
\> $CurrentJobList[0]
Name         Code
----             ----
19xx-Job1   19xx

\> $MisMatches = Compare-Object $jobList18Jun $CurrentJobList -Property name -PassThru
\> $CurrentJobList[0]
SideIndicator  Name       Code
-------------  ----       ----
=>             19xx-Job1  19xx

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18184766-c3b5-3f82-b4d0-8175a93cb3e3
* Version Independent ID: 85f1e969-8216-bed4-2204-409cbd9befd4
* Content: [Compare-Object (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/compare-object?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@JamesWTruher Is this a bug or a documentation error?

**Comment by weigh2tall** [comment]
Looks like it might be a bug, because I can produce "both" behaviors.

**Comment by mklement0** [comment]
It's not a bug, but something worth mentioning in the docs:

While the input types _are_ passed through with `-Passthru`, they are also _decorated_ with a `.SideIndicator` _ETS property_ (a `NoteProperty` member) - as opposed to being _wrapped_ in a different type (custom object).

There is currently no way to opt out of this decoration.

The workaround is to call `psobject.baseobject` on a decorated object.

**Comment by sdwheeler** [comment]
When PassThru is used, Compare-Object adds the SideIndicator noteproperty. Need to update docs.

**Comment by joeyaiello** [comment]
Took me a minute to figure out what you meant, but I get it now. It is a little funky that SideIndicator only gets added when `-PassThru` is used, but I suspect this is a implementation detail to make sure that the object isn't duplicated in memory for the purpose of `PassThru` (because e.g. filtration using `Where-Object` later in the pipeline after `-PassThru` is useful, if the SideIndicator isn't preserved, `Compare-Object` is useless with `-PassThru`)

Will talk to @JamesWTruher about this one later to confirm that's the case. But yes, I think we should just doc this behavior. 

Also curious about what happens if the object already has a SideIndicator property.

**Comment by mklement0** [comment]
@joeyaiello It's not necessarily useless without `.SideIndicator`, because sometimes the differences are by definition "one-sided", and sometimes you may not care what side they came from.
If you do care, however, then a `.SideIndicator` note property is obviously needed.

As an aside:
In general, this ties with the discussion about providing a `-Raw` switch to opt out of decoration; in this case `-Raw` could act like `-PassThru`, except without the note property. See https://github.com/PowerShell/PowerShell/issues/7855

> Also curious about what happens if the object already has a SideIndicator property.

If the pass-through object's `.SideIndicator` property is a `NoteType` property already (such as in `[pcustomobject]` instances), its value is effectively _overwritten_ (which may change the type) - the original value is _lost_:

```
PS> (Compare-Object -PassThru ([pscustomobject] @{ one = 1; SideIndicator = 42 })  @()).SideIndicator
<=
```

If the it's a regular property, it is  _quietly shadowed_ (hidden) by the `NoteProperty` member that `Compare-Object` adds:

```
PS> class Foo { [string] $one = 1; [int] $SideIndicator = 42 }
PS> (Compare-Object -PassThru ([Foo]::new())  @()).SideIndicator
<=
```

The only way to get at the underlying regular property in that case is to the call the `get_SideIndicator()` accessor method.

**Comment by joeyaiello** [comment]
> @joeyaiello It's not necessarily useless without .SideIndicator, because sometimes the differences are by definition "one-sided", and sometimes you may not care what side they came from.
> If you do care, however, then a .SideIndicator note property is obviously needed.

Ah yes, I missed the fact that the matching objects are omitted from the return of -PassThru. A more accurate statement is that `Compare-Object -IncludeEqual -PassThru` would be useless without `SideIndicator`. 

As for the overwrite case, I suspect that's suuuuper uncommon, and I'm sure it's worth filing a bug, but it's probably worth mentioning in the docs for `-PassThru`. If you or anyone you know have actually hit that one in the wild, feel free to file a bug on PS/PS with a bit of a scenario context.

Thanks!

**Comment by mklement0** [comment]
> As for the overwrite case, I suspect that's suuuuper uncommon, and I'm not sure it's worth filing a bug,  but it's probably worth mentioning in the docs for -PassThru

Makes perfect sense to me.

> Ah yes, I missed the fact that the matching objects are omitted from the return of `-PassThru`. A more accurate statement is that `Compare-Object -IncludeEqual -PassThru` would be useless without `SideIndicator`.

That reminds me: combining `-IncludeEqual` with  both `-PassTru` and `-Property`  introduces another behavior worth documenting:

`Compare-Object` then passes the _LHS_ through (`-ReferenceObject`), even though the matching RHS objects may have _non-compared_ properties with differing values.

Here's an example:

```powershell
class Foo { [string] $one = 1; [string] $two = 'A'; }
class Bar { [string] $one = 1; [string] $two = 'B'; }

Compare-Object -IncludeEqual -PassThru ([Foo]::new()) ([Bar]::new()) -property one 
```

The above yields:

~~~none

SideIndicator one two
------------- --- ---
==            1   A

~~~

Note how it is the `[Foo]` instance that was passed through (LHS), not the `[Bar]` instance (RHS), whose `.two` value differs.

**Comment by joeyaiello** [comment]
Noted, but that still seems like correct behavior. 

@sdwheeler I think the only actionable piece here is noting in the `PassThru` docs that `.SideIndicator` gets added.

**Comment by mklement0** [comment]
>  I think the only actionable piece here is noting in the `PassThru` docs that `.SideIndicator` gets added.

That, plus the fact that  when you combine `-IncludeEqual` with both `-PassTru` and `-Property`, it is the considered-equal _LHS_ objects that are passed through, irrespective of whether the RHS objects may differ with respect to the properties that were _not_ compared.

**Comment by mklement0** [comment]
As for why I think it's important to document  the behavior described in my previous comment, @joeyaiello:

* It is an inherently conceptually complex combination of parameters...
* ...and the resulting behavior involves an _ultimately arbitrary design decision_ that must be documented.

It is reasonable to assume that with `-IncludeEqual` you get _all data_ - yet in the described scenario you don't.

The unspoken design decision is to give precedence to the _LHS_ - but you could equally justifiably expect _both_ objects to be included, so as not to miss any data.

Therefore, it is important to document that design decision.
