### ISSUE TITLE
Inline help incorrect

### ISSUE THREAD

**Issue by Cormacolinde** [MicrosoftDocs/PowerShell-Docs#4572]
If I do get-help -detailed test-connection the description for parameter "TimeToLive" is incorrect:

"Specifies the maximum time, in seconds, that each echo request packet, or ping, is active. Enter an integer
between 1 and 255. The default value is 80 (seconds). The alias of the TimeToLive parameter is TTL ."

I tested and this is clearly incorrect. The text on this page is correct but does not correspond to the inline version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8da621a-dd94-e6e6-b789-df6ae6faf14d
* Version Independent ID: 4532edd3-5890-2ab7-a7eb-d366d0462d7e
* Content: [Update-Help (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/update-help?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Update-Help.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Update-Help.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
You need to run `Update-Help -Force` to get the new version of the help content. 

NOTE: We are only publishing updated help content for v6.x at time. If you run `Update-Help` for any older version it downloads the last published version. Help for v5.1 and older has not been update in a long time. You must visit the website for the latest documentation.

**Comment by kernelpickle** [comment]
Unacceptable!  That v6.x nonsense is NOT what ships with the current version of Windows!  I'm sorry, but NOBODY outside of the Windows environment wants to use PowerShell for anything if they can avoid it!  I guarantee that anyone who is trying to do remote admin work for a Windows system is already running Window, OR they're accessing remote servers with a full GUI (because that's the ONLY way Microsoft knows how to built a server OS!), or using some other sort of VM.  The much more likely scenario is someone with a corporate issued device with Windows, that NEEDS to do remote work on a Unix based system, that may not have a GUI--thankfully someone FINALLY made SSH possible from PowerShell, but the fact PuTTY even exists is evidence you people have been asleep at the wheel for WAY too long!

I can appreciate some of the things that are going to be introduced with version 7, but other than some parallel processing stuff, I can't see anything that hasn't already existed in a better terminal for YEARS now.

Microsoft needs to get their act together, because they can't even get aliases to work properly--WHY for the life of me, are the instances where I can take the exact same parameters and formatting, swap the ridiculously long version of the command for the much shorter/familiar alias, and get different results?!  THAT absolutely shouldn't happen, because the command is still the same little application and the name is simply the symbolic link that points to it!  Earlier today, I couldn't figure out WHY the alias ForEach worked better than % or full ForEach-Object version--but it does!  Now that I've updated the help files, I've got MORE info, but it's not any better and now the Help file doesn't even show ALL the aliases!  If I didn't already know that % meant ForEach or ForEach-Object, I'd have a hell of time figuring out what other people have written into their scripts that I'm trying to decipher!  Thankfully, there's Google--but I should've been able to find it in the damn manual!
