### ISSUE TITLE
Guidance on where trap is placed in scope

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/PowerShell-Docs#4611]
This simple script has nonsensical results:

```
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

this-is-an-error

$trapMessage = "Hello from trap!"

trap {
    write-host $trapMessage
    continue
}
```

You'd expect an error about this-is-an-error, but instead you get:

```
The variable '$trapMessage' cannot be retrieved because it has not been set.
At line:9 char:16
+     write-host $trapMessage
+                ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (trapMessage:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : VariableIsUndefined
```

Ideally the language would support this better (e.g. don't use trap until the point in code it is declared), but failing that the docs should provide some guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7dea14-ae5b-68c5-9a11-9dc4c2d7d174
* Version Independent ID: 780bf958-3add-6a30-d5b9-ea2ed719e0b5
* Content: [about_Trap](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_trap?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Trap.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Trap.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The problem in your example is that the error is occurring before the `$trapMessage` is assigned. So that assignment line is never executed. This is expected behavior.

**Comment by johndog** [comment]
This isn’t a powershell bug, this is a doc bug.  I know the behavior is by design, but it’s still nonintuitive and it needs to be documented.  The docs need to give guidance, saying that A) it doesn’t matter where you define the trap -- it is always in effect for the whole scope (much to my chagrine), and B) it should offer techniques to avoid the problem.

**Comment by sdwheeler** [comment]
I talked this over with the PS Devs and will try to come up with a good way to document this.

**Comment by sdwheeler** [comment]
@rjmholt Any input you can provide would be helpful.

**Comment by JamesWTruher** [comment]
we can provide guidance that traps _should_ be at the top of the scope (but after the param statement if present). We can think about an analyzer rule (FWIW, it's tricky since the AST doesn't give us quite enough info in an easily consumable way)

**Comment by johndog** [comment]
Here is another pseudo-code example for the start of .ps1 that actually motivated the bug:

```
param()

Import Utility.psm1
trap {ErrorHandlerFromUtilityModule $_}

# ... rest of script
```

If there was an error in importing the .psm1, you don't see it, you just scratch your head over the "function undefined" error message.  Any trap at script level runs the same risk, doesn't need to be a module import.

The sensible "trap should only be at the top" guideline effectively prevents doing interesting things in a trap at script level (anywhere else and you can just & {} to create a new scope or extract a new function without much consequence).  I don't know if that tension can be resolved with documentation.  Is it possible to craft a command in such a way that it would bypass a trap at current scope?

**Comment by rjmholt** [comment]
> Is it possible to craft a command in such a way that it would bypass a trap at current scope

Other than setting `ErrorAction`, no. And not just in the current scope, but in any parent scope to. It's the driving intent of a trap that it catches everything under its scope; it's a _trap_ and everything falls into it, at which point _it_ decides what happens.

Personally I dislike the fact that traps are hoisted like this and it strikes me as something of an oversight. But changing it in the language, either by making traps after the first statement a parse error or by making traps only apply to statements after it (which would be much harder to implement), would be a pretty big breaking change in the language.

Ultimately, traps have worked this way forever in PowerShell, and there hasn't been much demand from the community to change their functionality (the last time any change was suggested, there was not much enthusiasm and I got the impression there was annoyance we were discussing traps over other form of expression handling).

I think we definitely want to document that traps anywhere in a block will be hoisted so that they apply to all statements in that block and not just to those after it.

Ideally we could also write a PSScriptAnalyzer rule to check for this. However, this is complicated by the fact that [traps are hoisted at parse-time](https://github.com/PowerShell/PowerShell/blob/cf7699b4b9bb96bac906a7052f890d524f375677/src/System.Management.Automation/engine/parser/Parser.cs#L1820-L1908), so the data structure that holds the representation of the script to either compile or analyse it does not track what traps follow what statements (we are forced to use the extents instead).

**Comment by johndog** [comment]
Thanks for the details, @rjmholt .

Traps aren't great for error handling, but they _are_ nice for post-mortem error analysis (a bit of self-debugging).  It's a bit cruel when a trap intended to elaborate on an error winds up hiding it completely.

With that in mind, would it be feasible to change powershell to handle errors-within-trap differently?  Specifically, when entering a trap because of an error, "defer" the error until trap execution arrives at a resolution (either with break, continue or completion of the trap).  If an error occurs in the trap preventing a resolution from being determined, output the deferred error followed by the in-trap error, _then_ stop execution.  It's hard to imagine breaking someone with this (though not impossible) since perhaps the only difference would be one additional error generated into $Error.  Stack would otherwise unwind from error in trap the same way, with the same error.

**Comment by johndog** [comment]
It did occur to me to improve the more recent example above with -EA Inquire:

```
param()

Import-Module -EA Inquire Utility.psm1
trap {ErrorHandlerFromUtilityModule $_}

# ... rest of script
```

That bubbles the "unexpected" error to the surface immediately before the trap has a chance to swallow it.  Once it gets past that Import-Module line successfully, the trap is essentially valid.  Maybe this can be refined into a recommended approach for setting up minor dependencies for a trap before the trap is intended to run, in cases where it's required.

**Comment by doctordns** [comment]
IF you do add such a sample, PLEASE ensure you spell out the parameter name, so -ERRORACTION vs -EA.

**Comment by rjmholt** [comment]
> Traps aren't great for error handling, but they are nice for post-mortem error analysis (a bit of self-debugging). It's a bit cruel when a trap intended to elaborate on an error winds up hiding it completely.

That sounds like the original motivation for https://github.com/PowerShell/PowerShell/issues/6010.

I didn't follow your description entirely, but I think it would be best at this point to open an issue on PowerShell to ask for this.
