### ISSUE TITLE
uninstall-package:  only works on msi's?

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#4619]
So this command only works with the msi provider?  If I try to uninstall something like notepad++, it doesn't seem to do anything, but gives no error.

```powershell
get-package notepad*

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
Notepad++ (32-bit x86)         7.5.9                                             Programs


get-package notepad* | uninstall-package

get-package notepad*

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
Notepad++ (32-bit x86)         7.5.9                                             Programs
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a817657-9f6e-7f0c-0ce3-43e454f2ffc2
* Version Independent ID: d862d96e-3f2b-f903-f62d-454d614b83c1
* Content: [Uninstall-Package (PackageManagement)](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/uninstall-package?view=powershell-6)
* Content Source: [reference/6/PackageManagement/Uninstall-Package.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PackageManagement/Uninstall-Package.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
@SydneyhSmith - Can you comment?

**Comment by SydneyhSmith** [comment]
@jszabo98 thanks for opening this issue-- This occurs because NotePad++ is not installed using Windows Installer (msi), so it is found only by the Programs PackageProvider, not the MSI PackageProvider. The Programs PackageProvider does not implement uninstall - I am not sure why not. Seems like a bug to silently do nothing.

As a workaround,
`get-package *notepad* |% { & $_.Meta.Attributes["UninstallString"]}`
should work 

We are tracking this bug at https://github.com/OneGet/oneget/issues/435

**Comment by jszabo98** [comment]
What is OneGet?

**Comment by sdwheeler** [comment]
@jszabo98 OneGet is the original name of the packagemanagement code project.
