### ISSUE TITLE
Indicate how to restore it back to "default"

### ISSUE THREAD

**Issue by Vaccano** [MicrosoftDocs/PowerShell-Docs#4653]
I want to set this for a part of my script (to output a call).  But then I would like to put it back to "how it was".

It would be nice if this documentation indicated what the "Default state" is for the settings of this.  Is `-off` the default state?  Or is that more off than it was at default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312f0d72-2a6a-931e-f0b3-95d2aa76462e
* Version Independent ID: 7574a215-cb3f-fb75-199d-362ae1edd163
* Content: [Set-PSDebug (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-psdebug?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Set-PSDebug.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Set-PSDebug.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The default is `off`.

**Comment by biren1234** [comment]
out-file : Access to the path 'C:\Windows\system32\Debug.log' is denied.
At line:19 char:51
+         Get-AzureRmRecoveryServicesBackupJob 5>"$($FolderPath)\Debug. ...
+                                                   ~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], UnauthorizedAccessException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
 
Get-Content : Cannot find path 'C:\Windows\system32\Debug.log' because it does not exist.
At line:41 char:28
+         Foreach ($str in @(Get-Content .\Debug.log))
+                            ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\system32\Debug.log:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by sdwheeler** [comment]
@biren1234 What is your question?
