### ISSUE TITLE
Document Invoke-DscResource

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#4780]
Issue Details
-----------------

https://github.com/PowerShell/PowerShell/pull/10516
https://github.com/PowerShell/PowerShell-RFC/pull/214

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by bobbytreed** [comment]
@TravisEz13 I read through the links above, but was not able to come away with exactly what was fixed in Get-DSCResource.  

For Invoke-DSCResource, a doc update is needed for 7+ where you can invoke it without configuring the LCM, correct? Anything else?

I didn't see a final update on whether this allows use of non-CIM types for DSC resource parameters.
Would that be only for manual invoking of the command? Would the LCM still be dependent on CIM types for Resources?

**Comment by TravisEz13** [comment]
For PowerShell 7, LCM and CIM are not involved in `Invoke-DscResource`, this was explained in the RFC.  Nothing was fixed.  `Invoke-DscResource` was implemented.
