### ISSUE TITLE
PackageManagement MSI No Longer Supported

### ISSUE THREAD

**Issue by Stick97** [MicrosoftDocs/PowerShell-Docs#4811]
Please update this page to reflect new instructions for how to install for PowerShell 3.0 and 4.0 since the PackageManagement MSI is no longer supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bc5a9a-76fe-42f6-f11f-17e59af93f4f
* Version Independent ID: 8d0ef725-578d-bd63-8b4a-5a14a54f7dd4
* Content: [Installing PowerShellGet](https://docs.microsoft.com/en-us/powershell/gallery/installing-psget#feedback)
* Content Source: [gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-gallery**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by sdwheeler** [comment]
This is not the right place for that information. Installing those versions of PowerShell is already covered in the WMF articles.

**Comment by Stick97** [comment]
@sdwheeler, I'm not sure I follow. Instructions for how to install PowerShellGet for older PowerShell versions aren't appropriate on the documentation for installing PowerShellGet?

**Comment by sdwheeler** [comment]
No. The instructions for how to install WMF 3/4 are not appropriate in this location. But I think I see where the confusion lies. 

The current article documents how to upgrade from the preview version of PowerShellGet that was shipped in an MSI package. That package is no longer available and is not supported. The current versions of PowerShellGet should work on on PowerShell 3 and newer. 

The problem is if you have a system that is running PowerShell 3 or PowerShell 4 that does not have PowerShellGet installed then how do you get it?

The answer is that you have to get it from the PowerShell Gallery. You download the module using `Save-Module` on another system then copy the saved module to the machine running PowerShell 3 or 4. 

We can add this to the article.
