### ISSUE TITLE
Please add some valid scenarios for Invoke-Expression

### ISSUE THREAD

**Issue by moerwald** [MicrosoftDocs/PowerShell-Docs#4897]
If you use Invoke-Expression a lot of people will give you hints to replace it via the call-operator, because Invoke-Expression is vulnerable to injection attacks. If you google around a litte bit (https://www.google.at/search?sxsrf=ACYBGNRKWEYuSTUi5bXDIRG5TB6lvfOg_Q%3A1570373499294&source=hp&ei=e_-ZXeiOD63LmwW2irSgDA&q=invoke-expression+bad&oq=invoke-expression+bad&gs_l=psy-ab.3..0i22i30.296.3329..3455...0.0..0.123.1340.0j12......0....1..gws-wiz.......35i39j0j0i67j0i203.sX62H9eVhnY&ved=0ahUKEwiouNmU8YflAhWt5aYKHTYFDcQQ4dUDCAU&uact=5) you'll find a lot of posts mention this problem. It would be cool if this documentation would be extended to mention scenarios where it is useful to use this cmldet, and where it doesn't makes a lot of sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d669d38f-7692-bbaa-2c88-ba1b1d2bb4c1
* Version Independent ID: 9d592d60-e29c-84e6-2e43-078e2a69fb97
* Content: [Invoke-Expression (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-expression?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by mklement0** [comment]
Thanks, @moerwald - good suggestion, but it has been made before in #2679.

**Comment by rjmholt** [comment]
I agree with the sentiment in #2679 that we should warn about `iex`. Take a look at the JS documentation for comparison: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval.

There are probably a few layers of "I want to use Invoke-Expression":

- Trivially preventable: `cat ./file.ps1 | iex`. Cases where it's simpler to redirect PowerShell to execute something naturally. In these cases, a script or code will already exist in file or AST form, and it's just a matter of dot-sourcing it.
- Obscure to prevent: things like dynamically defining functions (still requires `[scriptblock]::Create()`) and the reason to prevent is performance not security. These are cases where it's easy to hit an API from the language but not from code. So for example it's easy to define a function in script, but hard to write script that calls the function definition API.
- Somewhat legitimate: uses that we shouldn't encourage but which do make life simpler. `iwr https://notmaliciouscode.com/assets/script.ps1 | iex` types of things. These should be interactive only.
- Legitimate: I can't think of anything beyond testing. We test for parse errors in PowerShell/PowerShell using `iex` because that's the only way to turn a parse-time error into a runtime one. I would imagine a similar trick works with class definitions in PowerShell, but in that case, the thing should be a file that's dot-sourced.

Bottom line: **We should have a red warning on Invoke-Expression saying it's dangerous and should only be used interactively. We should also try and list some of the class 4 cases -- I can only think of runtime vs parse-time errors**.

**Comment by sdwheeler** [comment]
Need to review existing docs and make it clear that Invoke-Expression is maintained for historical purposes but is effectively deprecated. We do not recommend its use but it is not being removed any time soon.

Tracking discussion in https://github.com/PowerShell/PowerShell/issues/11662

**Comment by rjmholt** [comment]
> Invoke-Expression is maintained for historical purposes but is effectively deprecated

My personal feeling (worth also talking to @SteveL-MSFT, @joeyaiello, @JamesWTruher and @brucepay) is that it’s not so much historical as an important part of an interpreted language. It’s dangerous, and shouldn’t be used in production, but all scripting languages have an `eval()` equivalent.

**Comment by sdwheeler** [comment]
Linking #2679

**Comment by mklement0** [comment]
As discussed in https://github.com/PowerShell/PowerShell/issues/11662, the more important task is to document examples of when _not_ to use `Invoke-Expression`, but here's my personal list of - exotic - cases where I have found use of `Invoke-Expression` justified, excerpted from https://stackoverflow.com/a/51252636/45375:

---

**_Rare_ examples of justified (safe) use of `Invoke-Expression`**:

* Creating PSv5+ custom classes *dynamically*:
  * [so that the class can be used in a remote session](https://stackoverflow.com/a/59923349/45375).
  * [so that the set of properties can be created based on conditions at runtime](https://stackoverflow.com/a/49117370/45375).


* [Using `Invoke-Expression` (with extra precautions) in combination with `Write-Output` to parse a string with embedded quoting](https://stackoverflow.com/a/51229037/45375).
