### ISSUE TITLE
Add documentation for `??`  `??=`  `?.` and `?[]` operators

### ISSUE THREAD

**Issue by adityapatwardhan** [MicrosoftDocs/PowerShell-Docs#4925]
# Summary of the new document or enhancement

Related to https://github.com/PowerShell/PowerShell/pull/10636

Details of requested document:

- Proposed title: Null coalescing operators
- Propose location in the TOC: 
- Target audience: developers
- Purpose or scenario: $x ?? $y and $x ??= 10
  _or_
  Proposed changes/additions to existing article:
- List of related articles to link to:

**Comment by sdwheeler** [comment]
The null-coalescing operator `??` returns the value of its left-hand operand if it isn't `$null`. Otherwise, it evaluates the right-hand operand and returns that result. The `??` operator doesn't evaluate the right-hand operand if the left-hand operand evaluates to non-null.

The null-coalescing assignment operator `??=` assigns the value of its right-hand operand to its left-hand operand only if the left-hand operand evaluates to null. The `??=` operator doesn't evaluate its right-hand operand if the left-hand operand evaluates to non-null.

@adityapatwardhan See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator. Can you provide similar use cases?
