### ISSUE TITLE
Explain -SourceID parameter of Write-Progress

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/PowerShell-Docs#5049]
So, what does the `-SourceID` parameter exactly do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b409d113-fd3a-ea1e-3959-93cecdd1ca27
* Version Independent ID: 01ff8fbd-8abc-1419-0f9e-d56ddff65429
* Content: [Write-Progress (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Write-Progress?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by rjmholt** [comment]
I can't speak to the intent (looks like the underlying code was written quite early in PowerShell judging by the style), but...

[This comment](https://github.com/PowerShell/PowerShell/blob/4b8462766f1f1def461543296d1c6f14f6b2b8cd/src/System.Management.Automation/engine/MshCommandRuntime.cs#L351-L358) in MshCommandRuntime indicates we use it internally to distinguish what cmdlet instance is writing progress.

It looks like it's to identify the operation that is in progress so that the UI thread can relate them back to the same progress. See [here](https://github.com/PowerShell/PowerShell/blob/4b8462766f1f1def461543296d1c6f14f6b2b8cd/src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs#L63).

So I'd say that the `-SourceId` parameter exists to override the automatic behaviour if you want to write progress to the same progress indicator from two places at once. Or possibly from multiple threads. I can't really imagine a good scenario for this though.

**Comment by sdwheeler** [comment]
```
foreach ( $i in 1..10 ) { write-progress -id 0 -sourceid 10 $i       
 foreach ( $j in 1..10 ) { write-progress -id 1 -parentid 0 -sourceid 20 "$i $j"
  foreach ( $k in 1..10 ) { write-progress -id 2 -parentid 1 -sourceid 30 "$i $j $k"; start-sleep -m 20 }
 }
}
```

**Comment by skycommand** [comment]
@rjmholt Thanks for the interesting find. In the past, I skipped `MshCommandRuntime.cs` because its SourceID was int64. But now that I am thinking it would be legitimate for [WriteProgress() to give an int32 for a parameter that needs int64](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteProgressCmdlet.cs#L108).

You can tell that I've never worked with large numbers in C#, can't you? 😉

**Comment by skycommand** [comment]
Final conclusion: This parameter is [arcane magic](https://en.wikipedia.org/wiki/Magic_(programming)). Don't touch. Closing.

**Comment by sdwheeler** [comment]
I think we can add a better example.

**Comment by skycommand** [comment]
@sdwheeler I must say I didn't expect this degree of enthusiasm, but alright. If you think it is worth the effort, please give it your best shot. But please... test your sample code in PowerShell ISE too! The result might surprise you.
