### ISSUE TITLE
Confusion in alternative to Boolean set to true

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/PowerShell-Docs#5310]
I'm finding this recommendation strange since switch parameters are said just above to be false by default anyway.  Is this page telling me that if I set a switch parameter to false, it will double-negative and become true?  I wouldn't have thought so...

"For sample, instead of setting the parameter attribute to a Boolean value of true, declare the property as the System.Management.Automation.SwitchParameter type, and then set the default value of the parameter to false."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c0cf21-252c-21ee-c95e-51bafacd8d76
* Version Independent ID: e11ed037-1058-698f-0402-439144512b1d
* Content: [Types of Cmdlet Parameters - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/types-of-cmdlet-parameters?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/cmdlet/types-of-cmdlet-parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/types-of-cmdlet-parameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
What it is trying to say is that since SwitchParameters default to false when not explicitly used on the command line, the usage of the parameter should be the negative (false) case. For example, if you want a parameter that prevent showing all values then you should reverse that logic. The SwitchParameter name should be `ShowAll` instead of `DontShowAll`. That way, in the default case where you do not want to show all values, you omit the parameter so that the value of `ShowAll` defaults to false. When you want to show all, you use the `ShowAll` parameter, which causes the value of the parameter to be true.

**Comment by JeremyTBradshaw** [comment]
I guess it's the wording "and then set the default value to false" that threw me off as it makes it seem like the guide is having you accomplish something by manually setting the switch to false when defining the parameter.  But I see what you mean, it is just describing that - by using a switch instead of a boolean, you are making the value be false by default.
