### ISSUE TITLE
Use of .PSM1 file within Role Capabiliites module manifest in example unclear 

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#5312]
Under the heading "Place role capabilities in a module" there is an example. This example creates a module and a module manifest. The manifest includes a RootModule "ContosoJEAFunctions.psm1". What is the purpose of this? Can a PSM1 file ADD additional functions to a JEA session? If the .PSRC file defines the role, what value does the root module add? 
It would be useful to see this explained on this otherwise awesome page!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a177616c-e5fe-2cce-5813-f2ce4f0150db
* Version Independent ID: 00c84eaa-e272-aea5-22cb-61c6978155c5
* Content: [JEA Role Capabilities - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/jea/role-capabilities?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/learn/remoting/jea/role-capabilities.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/jea/role-capabilities.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by PaulHigin** [comment]
@doctordns, @sdwheeler 
In this example, the module was created only for the purpose of containing the .PSRC file. The module doesn't need to be functional and in fact you don't even need the .psm1 or .psd1 files.  

I don't think this was a good design decision, but when a new PowerShell JEA host session is being created, if a .PSRC file is part of the configuration, then PowerShell uses the module search paths ($env:PSModulePath) to find the .PSRC file and load it.

It doesn't make sense to add a 'RoleCapabilities' folder in a random PowerShell module directory, but that would work.  Instead the example creates a 'dummy' Module directory and that directory contains the 'RoleCapabilities' folder and the .PSRC file, which can be discovered via PowerShell module path search.

As you can imagine this has been a point of confusion to a lot of users.  So for PowerShell 6, we have added a new 'RoleCapabilityFiles' parameter for the .PSSC file, where you specify the full .PSRC file path rather than just the filename.  E.g.,

```powershell
RoleDefinitions = @{ 'redmond\paulhi' = @{ 'RoleCapabilityFiles' = 'c:\SystemCapabilities\ServiceRole.PSRC' } }
```

We should definitely document this if it hasn't been documented yet.

**Comment by doctordns** [comment]
Thanks for this. But does this cause the error??

**Comment by sdwheeler** [comment]
@doctordns What error are you referring to?

**Comment by doctordns** [comment]
Sorry - in PowerShell 7, JEA is not working at Run Time.  https://github.com/PowerShell/PowerShell/issues/11538

I wondered if this point was the cause of the observed error in that report.;

**Comment by doctordns** [comment]
Also - just tried it, i did this:
```powershell
$P = 'C:\Foo\RKDnsAdmins.pssc'
$RDHT = @{
  'Reskit\RKDnsAdmins' = @{RoleCapabilitiesFile = $P}
}
$PSCHT= @{
  Author              = 'DoctorDNS@Gmail.Com'
  Description         = 'Session Definition for RKDnsAdmins'
  SessionType         = 'RestrictedRemoteServer'   # ie JEA!
  Path                = $P                 # the output file
  RunAsVirtualAccount = $true
  TranscriptDirectory = 'C:\Foo\JeaTranscripts'
  RoleDefinitions     = $RDHT     # RKDnsAdmins role mapping
}
```
But if I then create it, I see this:
```
PS C:\Foo> New-PSSessionConfigurationFile @PSCHT

New-PSSessionConfigurationFile: 
Line |
  14 | New-PSSessionConfigurationFile @PSCHT
     | ^ Invalid role capability key: RoleCapabilitiesFile. Make sure the role capability name is spelled correctly and is a valid session configuration property.
```

**Comment by PaulHigin** [comment]
Regarding Issue #11538, sorry I should have updated it, but I have found the issue and the problem is due to the WinRM layer not reporting the user token to the session, with the result that user cannot be validated for the specified role.  I am working on contacting WinRM team folks to find out why this not working as expected, but it seems to only occur on preview builds.  I should know more by next week.

Regarding the above error, the role capability hash key is misspelled.
It is 'RoleCapabilitiesFile'
But should be 'RoleCapabilityFiles'

Also the path has to be accessible in the account the session runs in, but you path should be.
