### ISSUE TITLE
Text Refers to Get-Container command that does not appear to exist

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#5544]
In the description of the ContainerID property, the text says "see the containers that are available to you, use the Get-Container cmdlet."

That command does not appear to exist. Bing/Google find little. There is an alpha module on GitHub, but that has not been touched for years. I suspect that the right answer is to use docker.exe to get the container IDs.

Two more things:
1. Whatever the command to find the ContainerID, can this page point a reference to the appropriate command in the Related Links Section. And maybe a hyperlink from that description as well?
2. Can we have an additional example showing this usage of the command?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1ec2a7c-6b25-8549-518c-424a48bcf1a3
* Version Independent ID: 723f8ac4-a696-8a16-7b01-79e991bb62bf
* Content: [Get-PSSession (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/get-pssession?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/Get-PSSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/Get-PSSession.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
We had the same problem in the `New-PSSession` doc and that one was fixed. Didn't see the problem here. 


### -ContainerId

Specifies an array of IDs of containers. This cmdlet starts an interactive session with each of the
specified containers. Use the `docker ps` command to get a list of container IDs. For more
information, see the help for the
[docker ps](https://docs.docker.com/engine/reference/commandline/ps/) command.

**Comment by doctordns** [comment]
Thanks!
Does the PR add an example using Container ID?
