### ISSUE TITLE
Example request for a PowerShell class declaration that implements a .NET Standard 2.1 custom interface

### ISSUE THREAD

**Issue by mdorantesm** [MicrosoftDocs/PowerShell-Docs#5691]
I have a .NET Standard 2.1 class library (mylib) with a defined interface `mylib.IMyInterface`.
I need to implement it with a PowerShell Core 7 class like this:

```
class MyPowerShell7Class : mylib.IMyInterface
{
   #. . .
}
```

Could you please point to the PowerShell Core 7 documentation that explains how to do that, i.e., to make my custom `mylib.IMyInterface` type visible at the declaration level of a PowerShell Core 7 script?

Thank you very much in advance for your help or any clarification.
Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65304a8f-89f7-f1f9-cad8-6cb0d36c5634
* Version Independent ID: a5651d52-5618-47e4-67df-6191278f0ad5
* Content: [about_Classes - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Have you referenced your assembly in your script? See `using assembly <.NET-assembly-path>` in https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_using?view=powershell-7

After that you should be able to resolve the `myLib` namespace.

**Comment by mdorantesm** [comment]
Thank you very much @sdwheeler for your response. It looks promising. I tried it. But something weird happened: first, I ran the following script with PowerShell Core 7 on c:\temp and it failed.
```
using assembly 'C:\temp\mylib.dll'

$rr = [deploy.MyClass]::new()
$rr.Operation1("some")
class XX1 : deploy.MyClass
{
}
$xx = [XX1]::new()
$xx.Operation1("some2")

```
OUTPUT:
```
ParserError: somescript.ps1:5
Line |
   5 |  class XX1 : deploy.MyClass
     |              ~~~~~~~~~~~~~~~~
     | At somescript.ps1:5 char:13 + class XX1 : deploy.MyClass +             ~~~~~~~~~~~~~~~~
Unable to find type
     | [deploy.MyClass].
```
Next, I commented from line 5 to the end and ran it again. This time it executed ok:
OUTPUT:
`MyClass.Operation1: some`

Next, I removed the commented lines and ran it again.This time it executed ok:
OUTPUT:
```
MyClass.Operation1: some
MyClass.Operation1: some2
```

What do you think I'm missing?

Thank you again very much in advance for your help.

**Comment by rjmholt** [comment]
Implementing an interface will work the same as extending a class, but all the interface members must be implemented. See [here](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md#interfaces) (@sdwheeler, it might be worth adding a note about needing to implement interface members in that section).

The type declaration will parse as long as the type is loaded. However, currently `using assembly` will only load the type at runtime, not parse time, as detailed in https://github.com/PowerShell/PowerShell/issues/2074. It remains a large work item since it requires us to implement a novel method of parsing .NET metadata without loading it.

This means that when you first execute your script, you get a parse error and it does not run. Then when you comment out the class declaration and run it again, it runs and loads the type. Then when you reintroduce the class declaration and run it a third time, the type is loaded so it succeeds.

In fact you get a nice message saying this if you use the PowerShell extension for VSCode:

![pssa](https://user-images.githubusercontent.com/7009879/78161261-091af000-73fa-11ea-8f30-d745c316654f.PNG)

A common workaround to all of this is to use dot-sourcing to allow the type to be loaded before you parse its type declaration:

### main.ps1
```powershell
Add-Type ./mylib.dll

. ./classes.ps1
```

### classes.ps1
```
class MyClass : mylib.IThing
{
}
```

**Comment by mdorantesm** [comment]
Thank you very much, @rjmholt .
The workaround worked, in my case, not with:
`
Add-Type ./mylib.dll
`
but with
`
Add-Type -Path ./mylib.dll

`

About a method of parsing .NET metadata without loading it. Do you mean other that this?
https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-load-assemblies-into-the-reflection-only-context

Best regards.

**Comment by rjmholt** [comment]
>  The workaround worked, in my case, not with:

Oh sorry, I forget that the default parameter set is from the source. I'll edit my comment in case others use it.

> https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-load-assemblies-into-the-reflection-only-context

The reflection-only context no longer exists in .NET Core. That's what Windows PowerShell uses and why it no longer works in PS 6+. Instead we must implement https://github.com/PowerShell/PowerShell/issues/6653

**Comment by mdorantesm** [comment]
Understood. Thank you for the clarification.
Best regards.
