### ISSUE TITLE
Incomplete documentation for Confirm

### ISSUE THREAD

**Issue by caspChristian** [MicrosoftDocs/PowerShell-Docs#5717]
There is no documentation, and even worse, no examples of how to use Confirm, or even if it can be used to not ask questions, 

Had to search on other sites to find examples of how it can be done https://stackoverflow.com/a/55918166/2716218

Please add clear examples of how to use -Confirm, especially since it does not conform to how any other of the arguments are provided.

If not, please answer these 2 questions:
* Where on the page is -Confirm explained that it needs -Confirm:$false and not something like -Confirm "No", or even better -NoConfirm
* Where on the page is it described that you can read about how -Confirm works on a different page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b8f2555-f3d4-1a06-55d3-0037a584d7da
* Version Independent ID: 0b18157a-a191-4733-90db-7dfceda2c99f
* Content: [Remove-Item (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
**Confirm** is a SwitchParameter. By default, SwitchParameters are **TRUE**  when you use them. So the pattern of `-Confirm:$false` is required. This is by design. 

The question is more about know when you will prompted. Prompting is the **Impact** level of an operation. The **Impact** and **Confirmation** systems are explained in the following docs:

-  [about_preference_variables](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7#confirmpreference)
- [about_functions_cmdletbindingattribute](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute?view=powershell-7#confirmimpact)

This other issue you have have run into is specific to `Remove-Item`. If you try to delete a folder that contains items and you have not used the **Recurse** parameter, the cmdlet will always prompt for confirmation and `-Confirm:$false` does not suppress the prompt. This is by design. However, if you provide the **Recurse** parameter, you will not be prompted and you do not have to add `-Confirm:$false`.
