### ISSUE TITLE
Relation to .NET projects?

### ISSUE THREAD

**Issue by zivkan** [MicrosoftDocs/PowerShell-Docs#5815]
[NuGet's docs on `Install-Package`](This topic describes the command within the Package Manager Console in Visual Studio on Windows. For the generic PowerShell Install-Package command, see the PowerShell PackageManagement reference.) says:

&gt; This topic describes the command within the Package Manager Console in Visual Studio on Windows. For the generic PowerShell Install-Package command, see the PowerShell PackageManagement reference.

Additionally, this page's entire description says "Installs one or more software packages", and if you come in with the mindset of installing a NuGet package into your .NET project, it sounds relevant. The name clash between PowerShell and NuGet's Package Manager Console is unfortunate, but I think it would be helpful if these docs did more to clear up the confusion.

I'd like to see improvements to these docs to explain what a "software package" is. Is it simply a distribution method for PowerShell modules, or is it more generic. Is it intended to be able to install NuGet packages into .NET projects? If not, given there is so much information on the internet about using Visual Studio's PMC to install packages via `Install-Package`, I think a quick note saying that this is not the command for that would be really helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e512130c-870a-77b7-2dda-fdbb1d2acc22
* Version Independent ID: 3b920543-f348-a9a4-93b2-5b3dd01532e8
* Content: [Install-Package (PackageManagement)](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-package?view=powershell-6#feedback)
* Content Source: [reference/6/PackageManagement/Install-Package.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PackageManagement/Install-Package.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you comment on this?

**Comment by sdwheeler** [comment]
The Package Management Console in Visual Studio is an instance of PowerShell 5.1 running in different host (Package Management Console Host). The **NuGet** module that runs there ships in Visual Studio and only works when used in the Package Management Console. Its version of `Install-Package` is dependent on information provided by the PM Console Host to that it can install NuGet packages into the current VS Project.

The `Install-Package` cmdet in the **PackageManagement** module can install any NuGet package from any NuGet (v2) server. But is does not put them into your .NET project. The main function of the **PackageManagement** module is to act as a provider for **PowerShellGet** cmdlets. While the **PackageManagement** cmdlets can be used independently, they are rarely used that way.

We are working on [PowerShellGet v3](https://devblogs.microsoft.com/powershell/powershellget-3-0-preview-1/). There will be less confusion in v3 because **PowerShellGet** and **PackageManagement** are being merged.

cc: @SydneyhSmith
