### ISSUE TITLE
Obsolete blurb light on information

### ISSUE THREAD

**Issue by rwilliamsit** [MicrosoftDocs/PowerShell-Docs#5936]
It says this is obsolete because "This cmdlet does not guarantee secure connections to SMTP servers." and offers a link to a page for more information.  The linked page doesn't contain more information about this issue.  Exactly why do you say that this cmdlet not guarantee secure connections?  Why should we use some other library instead of fixing this simple cmdlet?  Since this obsolete message doesn't contain any details on why it's obsolete it sounds like it's a simple issue that can be fixed with better TLS support or something?  Why isn't Microsoft upgrading the protocol support for this cmdlet or offering better defaults or something? Seems silly to obsolete this essential cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc928f9-c5cb-7743-725b-7fa024427992
* Version Independent ID: c6c8dfc2-ec43-2231-908a-3a7ac67aeb0b
* Content: [Send-MailMessage (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Send-MailMessage.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The issue is in the .NET class. The cmdlet can only rely on the .NET class that is available. The .NET team is no longer supporting the class and they have no plans to change that. See the linked note: [DE0005](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md.

The recommendation is to use MailKit. But MailKit while is an open source project from Microsoft, it has not yet been accepted into the .NET Core code base. So PowerShell cannot use it at this time.
