### ISSUE TITLE
How do I get local powershell and ssh powershell to behave the same?

### ISSUE THREAD

**Issue by greggman** [MicrosoftDocs/PowerShell-Docs#6078]
Why do I want  -NoProfile in the sshd_config file?

When I open a powershell locally I get all my profile settings
When I open a powershell via ssh to the same machine I get a bunch of errors of posh-git and oh-my-posh missing. 

When I do the same in Linux/MacOS the local shell experience is exactly the same as the remote ssh experience.

Shouldn't the default instructions should do the same for powershell? That would be the most expected thing to me at least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e79ea6-1d79-6147-aa3e-362b04bc7528
* Version Independent ID: 8877b05f-1f52-8c75-2d7d-5100cc52c4cb
* Content: [PowerShell Remoting Over SSH - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Using `-NoProfile` makes session startup faster for everyone that uses SSH for connections. You can always dot-source your profile in the remote session after connecting. If you are the only user, configure it how you want.

**Comment by greggman** [comment]
Sorry if I didn't make my point clear.

My point is ssh has existed for decades. How it works is well established. When I ssh into a box it runs my profile just as though I had started a shell locally.

The docs for Powershell should show how to setup Powershell the same as ssh so it behaves the same. The current docs do not. Even removing --NoProfile does not make sshing work the same as running locally which is how all other implementations of ssh work.

Can you please update the docs so that ssh on powershell works the same as ssh everywhere else. That there is no noticeable difference logging in locally (not over ssh) vs remotely (over ssh)?

**Comment by adityapatwardhan** [comment]
Can you give this a try: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7#-login---l

**Comment by sdwheeler** [comment]
I did some testing on this. This is not something that can be changed via configuration. In fact, removing `-NoProfile` doesn't changing anything. This issue is that the `$profile` variable is not populated. I don't know if this is caused by sshd or by pwsh running in SSH-mode. I suggest 
you an issue at https://github.com/PowerShell/PowerShell/issues/choose.

cc: @maertendMSFT @SteveL-MSFT

**Comment by sdwheeler** [comment]
Scenario: 

1. Set up SSH Client and Server on a Windows machine.
2. Configure SSH Server per the PowerShell remoting article, except do not use the -NoProfile option
3. On same machine, run ssh.exe to connect to localhost

Expected behavior - the ssh session should be an interactive PowerShell session and should run the user's profile.

Actual behavior - user is presented with a CMD shell

The CMD shell is the default shell for sshd if you have not set it in the registry. If you run pwsh from the CMD shell, the profile is loaded. If you create a new session using New-PSSession/Enter-PSSession, you get a PowerShell session, but the profile does not run and $profile is null.

If you set the default shell of SSHD to pwsh.exe , then the profile is executed, regardless of whether you use -NoProfile in the Subsystem configuration. Note also, if there is a Warning or Error in the user profile, the New-PSSession fails.

**Comment by sdwheeler** [comment]
@greggman - What is the `DefaultShell` set to in the registry? It appears that it may be set to `PowerShell.exe` and not `pwsh.exe`. Does your profile script work in PowerShell 5.1?

**Comment by greggman** [comment]
Thank you for looking into this.

Setting my default powershell in the registry gets things better but still not the same.

from cmd.exe to pwsh

```
Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\gregg>pwsh
PowerShell 7.0.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

Loading personal and system profiles took 620ms.
❯ (New-Object Security.Principal.WindowsPrincipal(
>>   [Security.Principal.WindowsIdentity]::GetCurrent())
>> ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
False
```

From cmd.exe to ssh localhost

```
Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\gregg>ssh localhost
gregg@localhost's password:
PowerShell 7.0.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

Loading personal and system profiles took 620ms.
❯ (New-Object Security.Principal.WindowsPrincipal(
>>   [Security.Principal.WindowsIdentity]::GetCurrent())
>> ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
True
```

For some magic reason when I ssh to pwsh I get admin but when I open locally I don't. 

So the question is still: "How do I get local powershell and ssh powershell to behave the same?"

**Comment by sdwheeler** [comment]
OK, this is a product issue that needs to be filed in either one of these repos
- OpenSSH - https://github.com/PowerShell/OpenSSH-Portable/issues
- PowerShell - https://github.com/PowerShell/PowerShell/issues/choose
