### ISSUE TITLE
Pull and improve tests for online help

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/PowerShell-Docs#6327]
# Documentation Issue

Pull tests for online help from the PowerShell project and improve them!
## Context of the issue

Online help pages for PowerShell are published by Microsoft using numeric identifiers.  Tests implemented for them currently only check that the URL of the online help page is defined; they do not check the content of the page, so it happens that the online help page describes unrelated generic content.  The PowerShell project [cannot and will not](https://github.com/PowerShell/PowerShell/issues/13177#issuecomment-661039803) test this functionality.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [X] Version 7.1 preview content
- [X] Version 7.0 content
- [X] Version 6 content
- [X] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

When I invoke `HELP PROMPT -O`, I get Microsoft’s main page.  This circumstance should cause the build to fail but it does not.

**Comment by sdwheeler** [comment]
I agree that we should have some more rigorous tests in the Docs repository. I will look into what we can do for this. But some of the issues cannot be avoided by testing.

In the current version of the help files, the `prompt` function does not have a HelpUri defined. So, `Help prompt -Online` throws this error:

```
Get-Help:
Line |
  64 |      $help = Get-Help @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
```

It does not take to you the main microsoft.com page. So the test you propose would not fail or would fail for a different reason. 

Fixing the "issues" require one or more of the following changes:
- code changes since the HelpUri is defined in the C# code of the cmdlet
- code changes in `Get-Help` to provide a better user experience
- target URL changes to the FWLink in our redirection system
- updates to the `Online version:` metadata in the markdown file for the cmdlet

Any code changes would be fix-forward only. Users would have to upgrade to see the benefit of the change.

**Comment by yecril71pl** [comment]
I do not understand the situation at hand—the URL for `prompt` is still defined in the master branch.  It can also be retrieved as `GET-HELP PROMPT | % RELATEDLINKS`.

**Comment by sdwheeler** [comment]
Sorry, I just realized that the `prompt` function on my system is overridden by the posh-git module. So that one has not link defined.

The link for the `prompt` function is one of the cases where the change has to be made in the source code to be fixed. The FWLink that is defined does not exist anymore. It was deleted from the redirection database. It cannot be recreated. A new link needs to be created and the code changed to use the new link.

**Comment by sdwheeler** [comment]
The CI job that did the tests in the docs repo has been removed. The CI job did build validation and published the cab files. The OPS build was doing the same validation and CabGen now does the publishing of the cab files. So the CI job is no longer needed.

We will revisit the need for tests after the redesign of PlatyPS.
