### ISSUE TITLE
Explicit Add-Type vs Implicit Add-Type Not Documented

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/PowerShell-Docs#6422]
There doesn't appear to be any documentation explaining when built-in types can be referenced and implicitly loaded via the bracket syntax, or when they need to be manually added to the session via Add-Type. 

Additionally, it's not clear how the type loading behavior differs between PowerShell Core and PowerShell Classic. 

For example, consider this command:
```powershell
$context = [System.DirectoryServices.AccountManagement.PrincipalContext]::new(
    [System.DirectoryServices.AccountManagement.ContextType]::Domain, 
    $Domain)
```

This command works fine on PowerShell Core, but fails on classic with:
```
Unable to find type [System.DirectoryServices.AccountManagement.PrincipalContext].
```

However, if I manually add the type before the call (via `Add-Type -AssemblyName System.DirectoryServices.AccountManagement`), it works fine on PowerShell Classic and PowerShell Core. 

It seems like there are some types that can be directly referenced, while others require the Add-Type call (and what is implicitly loadable is different between different versions of PowerShell). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d18806-064b-d668-dc7b-bab3d58223f8
* Version Independent ID: b550e1f5-2481-7908-1d62-607923d09a2b
* Content: [Add-Type (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Add-Type.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Add-Type.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by rjmholt** [comment]
I believe the breakdown is:

- In Windows PowerShell (i.e. 5.1 and below), you need to use `Add-Type` for anything that isn't already loaded. This is chiefly for scenarios involving GAC assemblies, which you can specify by name, rather than by path.
- In PS 6+, there is no GAC. But PowerShell now ships its own assemblies in `$PSHome`. These assemblies are automatically loaded on request, so there's no need to `Add-Type` them, but doing so is still permitted (it allows you to write scripts that are implicitly compatible with Windows PowerShell, like the example you give above).
- Since there's no GAC, there's no actual need in PS 6+ to use `Add-Type <type-name>`
- Loading assemblies from arbitrary paths still requires `Add-Type`, since those assemblies will not be discovered otherwise

@adityapatwardhan may know more details about this

**Comment by xtqqczze** [comment]
@rjmholt There is still GAC functionality in PowerShell 7.1, should this be reviewed?

>> 
>> 
>> They are for searching assemblies in GAC in the Parser, but I cannot remember exactly for what now.
>
>They are used in these files:
>
>https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/parser/Compiler.cs#L2791
>https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/parser/Parser.cs#L5079

_Originally posted by @xtqqczze in https://github.com/PowerShell/PowerShell/pull/13305#issuecomment-667210454_

**Comment by rjmholt** [comment]
> There is still GAC functionality in PowerShell 7.1, should this be reviewed?

Those lines are if-def'd out. `CoreCLR` is always true in our builds. See https://github.com/PowerShell/PowerShell/issues/4357
