### ISSUE TITLE
`$ErrorActionPreference` doesn't affect stderr output for native commands

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#6466]
# Summary of the new document or enhancement

The PR https://github.com/PowerShell/PowerShell/pull/13361 made a breaking change that `$ErrorActionPreference` doesn't affect stderr output for native commands.
Also the error records generated from the stderr output of native commands are not put in `$Error` and variable specified by `-ErrorVariable`.

- List of articles that need to be updated:
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/13361
- Link(s) to related issue(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/issues/3996

**Comment by SteveL-MSFT** [comment]
I think what needs to be said should be a bit more detailed on the user impact even though @daxian-dbw's content is technically correct:

- Previously, when stderr was redirected (like `ls foo 2>$null`), if the native command wrote to stderr, then it resulted in an ErrorRecord written to $Error.  This also meant that `$ErrorActionPreference` was affected by this ErrorRecord.  With PowerShell7.1, we recognized that many native commands write to stderr not as error messages, but an alternate stream for additional information that doesn't make sense to write to stdout.  This includes content such as verbose or progress output.
- I'm also working on a PR that is related to this and should be documented at the same time.  Because stderr is no longer a means to indicate a native command has error'd.  This means that `$?` which tells you if the last command succeeded or failed, should indicate succeeded if the native command exit code is 0 despite any content written to stderr.

**Comment by mklement0** [comment]
This information should eventually also be incorporated into the proposed conceptual help topic about calling external (native) executables - see #5152.

**Comment by chasewilson** [comment]
Just for Record and clarity, as of right now, this is an experimental feature and should be documented as such correct @daxian-dbw , @SteveL-MSFT ?

**Comment by mklement0** [comment]
Speaking of, @SteveL-MSFT:

Can we consider implementing this as a straight _bug fix_?

The current behavior is useless and counterintuitive:

If I execute `ls nosuch 2>$null` or `ls nosuch 2>err.txt`, the intent is clearly to silence / capture all stderr output - and not to _abort_ the command just because `$ErrorActionPreference` happens to be set to `'Stop'` (which without the `2>` redirection would have no impact on the command).
