### ISSUE TITLE
Not enough information on the pitfalls of PowerShell multi-dimension/single item arrays

### ISSUE THREAD

**Issue by plastikfan** [MicrosoftDocs/PowerShell-Docs#6504]
This artcile needs to be beefed up more with the hazards of Arrays in PowerShell, because arrays in PowerShell are not intuitive, not like most other programming languages and has plenty of trap-doors to keep you tearing your hair out for hours. Arrays in programming are not complicated, not even multi-dimensions. However, in PowerShell, arrays are unecessarily complicated and way too error prone; given this, the official documentation should reflect this and cover all bases.

- single item arrays
- @() operator, when it is needed when defining single item arrays
- , op and its use for defining single item arrays
- also, another big gotchya is touching an array already known to be a single item array, which is initialised correctly, then referenced again being passed on. This was a big headache for me. This should be documented.

Take this example case I wrote for a Pester test case:

_A lesson about single item arrays, every time you touch a single item array, you must use the comma op. It is not a case of set it and forget it:_

```powershell
        Mock get-AnswerAdvancedFn -ModuleName Elizium.Loopz {
          $pairs = @(, @('Author', 'Douglas Madcap Adams'));
          $first = $pairs[0];
          Write-Host "=== SINGLE-ITEM: pairs.count: $($pairs.Count), first.count: $($first.Count)"
          ([PSCustomObject]@{ Pairs = $pairs })
        }
```

The above won't work, because of the fault assigning **$pairs** to **Pairs**  even though we've used the correct syntax setting **$pairs** to **@(, @('Author', 'Douglas Madcap Adams'))**

The following fixes this issue, everytime you touch the single item array, you must use the comma syntax, otherwise you give PowerShell another chance to flatten your array:

```powershell
        Mock get-AnswerAdvancedFn -ModuleName Elizium.Loopz {
          $pairs = @(, @('Author', 'Douglas Madcap Adams'));
          $first = $pairs[0];
          Write-Host "=== SINGLE-ITEM: pairs.count: $($pairs.Count), first.count: $($first.Count)"
          ([PSCustomObject]@{ Pairs = , $pairs })
        }
```

My test code ended up being this:

```powershell
        Mock get-AnswerAdvancedFn -ModuleName Elizium.Loopz {
          ([PSCustomObject]@{ Pairs = , @(, @('Author', 'Douglas Madcap Adams')) })
        }
```
**Note, we had to use the comma op twice and both of those are necessary**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da50f473-b315-4af8-ee5c-a37abb01f19e
* Version Independent ID: ab878bfa-19e1-2011-aaf8-37456f420ddb
* Content: [about_Arrays - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
I'm not seeing any errors or issues with your example. I do get different output when using the commas but without the comma, I actually get the more expected bahavior. 

Running the first example:
```powershell
$pairs = @(, @('Author', 'Douglas Madcap Adams'));
          $first = $pairs[0];
          Write-Host "=== SINGLE-ITEM: pairs.count: $($pairs.Count), first.count: $($first.Count)"
          ([PSCustomObject]@{ Pairs =  $pairs })
```
gives me this:
```Output
=== SINGLE-ITEM: pairs.count: 1, first.count: 2

Pairs
-----
{Author Douglas Madcap Adams}
```

Running the second gives me this:
```Output
=== SINGLE-ITEM: pairs.count: 1, first.count: 2

Pairs
-----
{System.Object[]}
```

I'm not sure what is unexpected here. 
- single item arrays
  - This is already covered in the document. 
- @() operator, when it is needed when defining single item arrays
  - Covered in the document and stated to use when creating a single item collection
-  op and its use for defining single item arrays
  - Covered in the doc for a general use. Creating a single or zero item array can be useful if you don't know how many obejects you might get. 
- also, another big gotchya is touching an array already known to be a single item array, which is initialised correctly, then referenced again being passed on. This was a big headache for me. This should be documented.
  - I don't know what your headache was here. Even in your examples, PowerShell never lost track that there was 1 object in the array and then in that object there were two obects? 

Feel free to reach out to discuss further and clarify/correct if I've gotten something wrong here.

**Comment by plastikfan** [comment]
Unfortunately, I no longer have the log of errors that were generated. The error is not apparent at this point. The error comes when processing Pairs subsequently. The main issue here as I said before is refering to the $pairs variable, without actually using comma appropriately, because PowerShell sees this as an opportunity to flatten out the array. This is not documented and I thought it was with code at the other end of the chain processing it, rather than the real culprit of the Pairs =  $pairs.

Here is the code that processes the 2 dimensional Pairs collection:

```powershell
    if ($invokeResult -and $invokeResult.psobject.properties.match('Pairs') -and
      $invokeResult.Pairs -and ($invokeResult.Pairs -is [Array]) -and ($invokeResult.Pairs.Count -gt 0)) {
      $themedPairs += $invokeResult.Pairs;
    }
```

The _$themedPairs += $invokeResult.Pairs_ is the line that breaks (even though it is correct) if the $pairs is incorrectly handled.

Specifically, multi-dimensional arrays with a single item in a particular dimenion. Thats not in there anywhere. Had to resolve this via lots of trial and error and guessing and making assumptions. Not good.

@() operator is sometimes a no op. If PowerShell thinks the item you are applying this op to is already an array, it does nothing. This is a problem for multi-dimension arrays.

Considering the headaches of 1 item arrays in PowerShell, the paragraph **Arrays of zero or one** is simply not enough (it neither mentions the comma op or @() op); it needs more comprehensive explanation given that the PowerShell implementation of arrays flies in the face of most programming languages. As I said, arrays are not complicated except in PowerShell; I know of no other language where special case has to be made for 1 element collections and automatic array flattenening. 

And I must re-iterate, and contradict your assertion that single item arrays are covered. Sure there is a paragraph entitled 'Arrays of zero or one', but it practically says nothing, so much so, it may as well not be there.

The reason I raised this was to give you feedback; afterall, thats the reason you put that link in your pages. Also, I can see many people run into these issues and have to resort to searching on stackoverflow, because the offiicial docuemtation is not comprehensive enough for a fundamental feature (arrays).

I'm just trying to give you constructive feedback :)

**Comment by chasewilson** [comment]
The feedback is appreciated. We do want the docs to be as clear as possible and rely on feedback like this to help. One of the things we try and balance is to get the information to as complete as possible without trying to cover every edge case which could "Muddy the waters" so to speak. This could make it hard for users of different experience levels be able to use the content effectively.

My intent isn't to shut feedback down, but to try and get down to the core issue and not just the scenario to be able to make it as universal, yet as helpful as possible. I also want to make sure I am not misreading or misunderstanding the feedback so I don't discount something I may be missing. 
 
I agree there are things to clarify and I'll try and lay them out. If I'm missing or misundrstanding something, please feel free to add or correct and we'll see how this goes. 

### This will initiate as a flat array

```powershell
$bad = @(@('This', 'Thing'))
```

### This will initiate as an array of an array

```powershell
$good = @(, @('These', 'Things'))
```

The comma isn't apparent in the documentation and should be clarified. This is actually definitely an area that can be clarified more in the documentation because I had to do some digging to get here:

`@()` doesn't actually construct the array. It, as the documentation states but doesn't necessarily make clear, is a **Sub-Expression Operator** and executes whatever is inside of it as a series of statements and ensures the output is an array.  So `$array = @(@(1,2))` will take the innermost array and send it as output to the outer ones where , if they outer layers aren't actually constructed arrays, is flattened. However, `@(, @(1,2))` creates an extra layer with the comma and elevates the inner expression into a second order array. So, the comma is actually doing the work and the outter `@()` is unneccessary. The following will work just as well: `$array = ,@(1,2)`.

The `@()` has it's own section, [The Array Sub-Expression Operator](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays?view=powershell-7#the-array-sub-expression-operator and needs to be updated to convey that behavior and can be referenced in the single object array section.

So, so far I have:

1. Adding the comma (`,`) and it's purpose in single item arrays
2. Clarifying the `@()` section and referencing it in the single item array section. 

I believe that clarifies the behavior you are facing in your scenarios but want to be sure? 

I really do appreciate the feedback, patience, and detailed responses because they help clarify and direct where we can improve. In the end, the result is a much better product that is hopefuly more complete and even easier to understand. I look forward to hear from you and we'll get this straightened out.
