### ISSUE TITLE
Print debug information during Configuration

### ISSUE THREAD

**Issue by eocern** [MicrosoftDocs/PowerShell-Docs#6510]
I am new to the "Configuration" capability for DSC provided. I am just trying to use it and have troubles so I was wondering is there a way to print a verbose or debug information during the "Configuration" execution. I tried to use -Verbose/ -Debug but it did not show me anything more. Few words about that on the information page will be helpful. 
In my case I have few variables within "foreach" loop of which I would like to print the values during the configuration.

Thank you,
Emo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 318415ee-6564-ce08-9b86-a1025e3a5f19
* Version Independent ID: e50055f0-88b7-af0e-30a9-ff3dd3729ad6
* Content: [DSC Configurations - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/configurations/configurations?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/configurations/configurations.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/configurations/configurations.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Are you talking about when the MOF is being created, or when the MOF is being applied (Changes actually being made to your environment)?

If you are talking about when the changes are being made, all verbose and debug statements that are passed to the stream are from the DSC Resources themselves and you don't have control over them unless you write a resource yourself. If you are talking about when the MOF is being created, which should only run once unless edited, that works as normal but not really standard practice because there aren't any changes being made in the configuration, it's just to creat a MOF. 

I'll be closing this for now but keeping an eye on it to answer any questions you have or be able to reopen if needed.
