### ISSUE TITLE
Document the structure of the XML document produced by ConvertTo-XML

### ISSUE THREAD

**Issue by jcflack** [MicrosoftDocs/PowerShell-Docs#6612]
# Documentation Issue

The `ConvertTo-XML` help topic does not document, or link to any documentation of, the XML document structure that is produced.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md
- Issue affects the following content (check all that apply):

**Cmdlet reference & about_ topics**
- [x ] Version 7.1 preview content
- [x ] Version 7.0 content
- [x ] Version 6 content
- [x ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

Issue #3310 pointed out that the `ConvertTo-XML` help topic could be easily misread to suggest that the XML structure produced was the same as what is produced and used by `Export-Clixml` and `Import-Clixml`, when it clearly is not.

The improvement suggested in #3310 had two parts:

* Clarify that the XML formats differ and there's (at least currently) no way to make `ConvertTo-Xml` emit CLIXML
* Describe the actual format, ideally with examples of real-world tools that can consume this format.

The pull request #5585 fixed the first part; the help topic now states more clearly that the mystery format is not the same as CLIXML. That is an improvement.

Issue #3310 was then closed without addressing the second part and without a rationale for leaving the second part unaddressed.

As a result, in its current form, the `ConvertTo-XML` help topic makes clear that the format produced is not CLIXML (and therefore that the existing CLIXML schema is no help in understanding it), but provides no documentation, or link to documentation, of the format it does produce. The help topic now says "`ConvertTo-Xml` returns an in-memory representation of an XML document, so you can continue to process it in PowerShell", but of course you can "continue to process it" only the way you would "process" some unknown XML format for which no schema or documentation is available.

The help topic should:

* Describe the actual format, ideally with examples of real-world tools that can consume this format. If an XML Schema (or RELAX NG, or any form of schema) exists for the format, a link to such schema should be included.

A [StackOverflow question](https://stackoverflow.com/questions/62970329) (now deleted) was opened in July to find if anyone could locate documentation of this format; no useful answer was ever submitted. It attracted a few comments revealing that there are still people who mistakenly think the format is CLIXML (and a page on SS64 still mistakenly says so).

**Comment by mklement0** [comment]
Thanks, @jcflack - ultimately, I think the `ConvertTo-Xml` cmdlet is a dead end, given that there's no matching cmdlet - or even external tooling I'm aware of - to parse its output.

Note that https://github.com/PowerShell/PowerShell/issues/3898 green-lighted `ConvertTo-CliXml` and `ConvertFrom-CliXml` cmdlets to complement their `Export-*` counterparts with in-memory variants, but so far no one has implemented them.

**Comment by chasewilson** [comment]
@jcflack, thanks for the feedback.
The link to the .NET class used [system.xml.xmldocument](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmldocument) is what is available for the the make up of the in memory representation. if you think there is more information that is need from there or could be linked from there, I suggest creating an issue for the page linked above. 

I'll be closing this for now, but feel free to respond and if needed, I'll reopen and continue to work through it. 

Thanks again and have a great one.

**Comment by mklement0** [comment]
@chasewilson, the link to `XmlDocument` doesn't help. What @jcflack  is looking for is  how the _specific structure_ of the resulting XML documents is  _derived from the specific input object types_.

Given the absence of a matching _de_-serialization cmdlet (or other tools) and the absence of documenting how input types are mapped onto XML documents, the resulting documents are virtually useless.
(By contrast, because `Export-CliXml` has a matching `Import-CliXml` cmdlet, one doesn't even have to care about the specifics of the XML)

In the absence of tooling, documenting the XML structure (mapping algorithm) would at least allow users to roll their own (possibly simplified and selective) tooling.

In the absence of documentation, the only - suboptimal - option is to conduct one's own experiments and _infer_ the algorithm or to study the specific resulting structure for specific input types of interest.
Also, the absence of documentation makes one wonder whether the mapping algorithm will stay the same over time.
(The even less desirable alternative is to study the [source code](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/CustomSerialization.cs).)

---

To give end users fair warning, I suggest updating the `ConvertTo-Xml` topic with a condensed version of the above, along the lines of: 

* no deserialization tools exist
* study the resulting XML documents to implement your own
* alternatively, use `Export-CliXml` and `Import-CliXml`, which, however requires saving the XML to a (temporary) _file_.
