### ISSUE TITLE
Documentation for Out-String cmdlet in Powershell 7

### ISSUE THREAD

**Issue by JohnFAsh** [MicrosoftDocs/PowerShell-Docs#6674]
Documentation obscurities in the Powershell-7 Output-String page at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-string?view=powershell-7 (as read on 25th September 2020):

1. The note to Example 2 states "The Width parameter is set to 100 characters per line to prevent truncation.". But the documentation for the -Width parameter states "Any additional characters are truncated, not wrapped.". Presumably this is the correct version?

2. In the overall Notes at the bottom of the page, it comments "The Out cmdlets don't have parameters that accept names or file paths.". This is untrue (Out-File has -FilePath and --LiteralPath parameters to specify where its output goes). What I think the comment means is that the Out cmdlets don't have such parameters to specify their input. None of the other Out- cmdlet pages have this unhelpful comment, even though their inputs are all specified in the same way.

I hope this is helpful;
Regards,
	John Ash

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com Γ₧ƒ GitHub issue linking.*

* ID: 8b57a9a7-8ae1-232b-6bbc-b8d5ea8ee398
* Version Independent ID: 1925a288-f947-4a6e-cf91-8b106ef9e493
* Content: [Out-String (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-string?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Out-String.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/live/reference/7.0/Microsoft.PowerShell.Utility/Out-String.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by mklement0** [comment]
Re 1. 

Whether a `-Width` argument _results in_ or _prevents_ truncation in a given situation depends on the input objects, and the existing example 2 - meant to demonstrate prevention - isn't well chosen, because truncation wouldn't occur either way.

A better example would be something like:

```powershell
# Assuming your terminal is less than 231 chars. wide (the extra 31 chars. are for the first column, 'Name'),
# the output would be truncated without the -Width argument.
@{ foo = 'x' * 200 } | Out-String -Width 250
```

Re 2.

I think the entire content of the "Notes" section isn't really necessary (and confusing in its current form), not least because it is so abstract.

If a higher-level commonality among cmdlets needs to be documented, it should be done in a _conceptual_ topic (which can be linked to).

**Comment by mklement0** [comment]
It's good to see issues getting resolved so quickly.

However, the resolution was incorrect: 

> Any additional characters are wrapped to the next line.

Whether wrapping or truncation occurs depends on the (possibly implicitly) applied `Format-*` cmdlet:

* _Truncation_ (with `…`)  only ever applies to (implied) `Format-Table` and `Format-Wide` formatting.

  * That's why I proposed  `@{ foo = 'x' * 200 } | Out-String -Width 250`, because it implicitly uses `Format-Table`, and the `-Width` argument indeed prevents truncation.

* _Line-wrapping_ applies to:
    * _all other_ `Format-*` cmdlets, notably the implicitly used `Format-List` in example 2.
    * _out-of-band_ formatted objects: `[string]` (printed as-is) and .NET primitive types and similar property-less value types such as `[decimal]` and `[bigint]` (printed as-is via `.ToString()`)

There are many more things worth correcting in this topic, but I'll address them separately.

**Comment by mklement0** [comment]
Please see #6679
