### ISSUE TITLE
UTC UNIX-Timestamp

### ISSUE THREAD

**Issue by buczoprazy** [MicrosoftDocs/PowerShell-Docs#6680]
Where is information about command to get UTC UNIX-Timestamp please?

**Comment by sdwheeler** [comment]
Take a look at the `Get-Date` cmdlet. The `-UFormat '%s'` parameter returns the timestamp in Unix format (Seconds elapsed since January 1, 1970 00:00:00). PowerShell v7.1 adds `-AsUTC` and `-UnixTimeSeconds` parameters that make conversion easier.
See https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/get-date?view=powershell-7.1

```
PS> Get-Date

Monday, September 28, 2020 6:54:01 AM

PS> Get-Date -AsUTC -uFormat '%s'
1601294041

PS> Get-Date -UnixTimeSeconds 1601294041

Monday, September 28, 2020 6:54:01 AM

PS> Get-Date -AsUTC -UnixTimeSeconds 1601294041

Monday, September 28, 2020 11:54:01 AM
```

**Comment by buczoprazy** [comment]
Is this for you unix timestamp?
`Monday, September 28, 2020 11:54:01 AM`

**Comment by sdwheeler** [comment]
No `1601294041` is the Unix timestamp for that date.
