### ISSUE TITLE
PowerShell remoting over SSH -  Windows to Linux

### ISSUE THREAD

**Issue by dreic** [MicrosoftDocs/PowerShell-Docs#6688]
# Documentation Issue

In [documentation ](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7) there are several examples of SSH usage but not for connecting from Windows to Linux using ssh key without powershell being present on Linux.

In this [document](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssession?view=powershell-7), parameter Subsystem is not explained well. What are the possible values for Linux or Network device that accept SSH connections (but no powershell present) ?

## Context of the issue

- URL to the article (Docs or GitHub URL): 
https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7
(https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssession?view=powershell-7

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [* ] Version 7.1 preview content
- [* ] Version 7.0 content
- [* ] Version 6 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

I am trying to connect from Windows host (AWS Lambda .NET core 3.1 function in the end) to Cisco Network device and execute some commands or connect to Linux Centos 7 but since documentation is not detailed about this scenario I am failing to connect. The problem is `the background process reported an error with the following message: The SSH client session has ended with error message: subsystem request failed on channel 0`. I am assuming New-PSSession expect starting a remote powershell process on which I connect and since there is no powershell there this fails.

**Comment by SteveL-MSFT** [comment]
There are three parts to using PowerShell remoting over SSH.  Doesn't matter if Windows or Linux:

1. PowerShell 7 need to be installed on both the client side and target side
2. sshd_config is [configured with the correct subsystem ](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7#set-up-on-an-ubuntu-1604-linux-computer)
3. `New-PSSession -Hostname` [is used](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7#powershell-remoting-example) (instead of -ComputerName)

I think the only issue I notice in the docs is where the last part has Linux->Linux, Linux->Windows, and Windows->Windows.  Each of those examples should work the same regardless of the client OS and the target OS.  So perhaps the samples should just be showing an interactive session using `Enter-PSSession` and an automation example using `New-PSSession` and `Invoke-Command`

**Comment by dreic** [comment]
I might have missed the the use of cmdlet, it's for establishing PS session not SSH session.

**Comment by sdwheeler** [comment]
@dreic Yes, this article is about doing PowerShell remoting using SSH instead of WinRM. If you need a simple remote terminal session from Windows to Cisco or Linux then you just use any SSH-enabled terminal client.
