### ISSUE TITLE
New-SelfSignedCertificateEx.ps1

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/PowerShell-Docs#6856]
New-SelfSignedCertificateEx.ps1 needs to be rehosted if it is still relevant. TechNet Gallery is shutting down. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea347ad-ed24-0760-8b3f-90ac72ddcec9
* Version Independent ID: b9a46e46-9263-f8e8-54b6-ab9a618819cc
* Content: [Securing the MOF File - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/pull-server/securemof?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/pull-server/secureMOF.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/pull-server/secureMOF.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by juvtib** [comment]
@Crypt32 
Is [Script Self-signed certificate generator (PowerShell)](https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6) still relevant to "[Securing the MOF File - PowerShell | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/scripting/dsc/pull-server/securemof?view=powershell-7)"?

**Comment by Crypt32** [comment]
The script on TechNet gallery is outdated. Since TechNet Gallery is in read-only mode I can't update it.

However, `New-SelfSignedCertificateEx` is still maintained as a part of [PowerShell PKI](https://github.com/PKISolutions/PSPKI) module. This module is downloadable from PowerShell gallery: https://www.powershellgallery.com/packages/PSPKI/.

The syntax is nearly same except SAN extension: https://www.pkisolutions.com/tools/pspki/New-SelfSignedCertificateEx/. Now, it requires a SAN type prefix. For example, for DNS Name type use `-SAN "dns:$($env:ComputerName)"` syntax.
