### ISSUE TITLE
Write-EventLog is deprecated in PowerShell Core 7.1  -- can you suggest a replacement?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/PowerShell-Docs#7033]
I noticed that this cmdlet is deprecated in PowerShell Core 7.1.  Searching around the internet seems to suggest that you can possibly replace this by[Importing Windows PowerShell modules in PowerShell Core](https://github.com/PowerShell/PowerShell/pull/10973).  If that is true, can you update this documentation to suggest how to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48528370-595d-20a1-024a-e2cfdc42db2c
* Version Independent ID: 788288b6-b6f8-804d-3252-51b5f23d9980
* Content: [Write-EventLog (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/write-eventlog?view=powershell-5.1&viewFallbackFrom=powershell-7.2)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Write-EventLog.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Write-EventLog.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @MarkIannucci . Thanks for the feedback. As you mentioned, Write-EventLog is depracated. Hoever, you can use [New-WinEvent](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/new-winevent) to accomplish your needs. Please feel free to respond if you have anymore questions or open a new issue if you have anymore feedback :)

**Comment by MarkIannucci** [comment]
@chasewilson , thank you.  I work at a hospital and am writing code to help vaccinate my colleagues.  Closing this issue contributed to my work.

**Comment by chasewilson** [comment]
@MarkIannucci Thats amazing to hear! Keep up the great work, stay safe out there, and good luck in this process. Don't hesitate to reach out if we can help any further.

**Comment by KevinMcCullen** [comment]
@chasewilson, I am a colleague of @MarkIannucci and have an additional question about your suggested solution.
Another colleague(@brandonmcclure) of ours wrote a [custom logging function that uses Write-EventLog](https://github.com/brandonmcclure/friendly-chainsaw/blob/master/Modules/FC_Log/Public/Write-Log.ps1) and we use this custom function in a number of different use cases, on different servers running different versions of PowerShell. 
Most of our PowerShell scripts work with PowerShell 5.1 but the script this post is regarding requires PowerShell 7.0 because it uses the UseQuotes parameter with the Export-Csv cmdlet.
I'm reluctant to re-write the custom logging function to use New-WinEvent because Write-EventLog work for 99.9% of our needs. 
Do you have any other suggestions on how we could possibly continue to use Write-EventLog with PowerShell Core 7.1?

**Comment by MarkIannucci** [comment]
@chasewilson to close this out, we did find a quick workaround.  We added `Import-Module Microsoft.PowerShell.Management -UseWindowsPowerShell` to our script and we're able to get past our issue while we work on the upstream problem.

**Comment by chasewilson** [comment]
@MarkIannucci @KevinMcCullen Great to hear! I'm glad it worked out for you both in the end:)
