### ISSUE TITLE
Confusing last code example in "ShouldProcess -Force"

### ISSUE THREAD

**Issue by Dottn** [MicrosoftDocs/PowerShell-Docs#7291]
The last code example in "ShouldProcess -Force" is identical to "ShouldContinue -Force", yet the last paragraph of "ShouldProcess -Force" explicitly states that the two should be implemented differently, and that the "ShouldContinue -Force" implementation is an anti-pattern for "ShouldProcess -Force".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953c600a-59d4-09aa-5dce-b41559a4c697
* Version Independent ID: 530b7644-3211-0f7c-3c63-d9959a72f541
* Content: [Everything you wanted to know about ShouldProcess - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
In the last paragragh of the [ShouldProcess -Force](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess?view=powershell-7.1#shouldprocess--force) section, it is saying that's what you should _NOT_ do. Specifically because **Force** will take priority and it shouldn't with `ShouldProcess`. 

However, **Force** _SHOULD_ take priority with `ShouldContinue` so that is how you should implement it with `ShouldContinue`. 

Does that answer your question?

**Comment by chasewilson** [comment]
I'm closing this issue for now but will be monitoring it for more feedback and will reopen if necessary.

**Comment by GraphiteWingedBird** [comment]
I came here for the same reason, and although I think you've answered my question - it is still confusing to have the sample code block written 'incorrectly' without a large call out that folks should avoid that. It is slightly more confusing because the paragraph directly following the "Don't Do This" code seems to be a continuation of an earlier thought and it doesn't address the bad example at all. I.e. if you go directly to that block of code and just start reading, it isn't clear which approach 'this approach' is referring to. Looking at only the code block and the two paragraphs underneath, you're led to believe that 'this approach' is the code block, which is the exact opposite of what you want users to walk away understanding.

`if ($Force -or $PSCmdlet.ShouldProcess('TARGET')){
        Write-Output "Some Action"
    }`

_If someone specifies both -Force and -WhatIf, then -WhatIf needs to take priority. **This approach preserves -WhatIf processing because ShouldProcess always gets executed.**

Do not add a check for the $Force value inside the if statement with the ShouldProcess. That is an anti-pattern for this specific scenario even though that's what I show you in the next section for ShouldContinue._

![image](https://user-images.githubusercontent.com/81541678/134419720-d360b05d-0eec-400c-b32c-0d28b2738351.png)
