### ISSUE TITLE
Pipelining examples ordering is reversed?

### ISSUE THREAD

**Issue by jerryKahnPerl** [MicrosoftDocs/PowerShell-Docs#7816]
seems like the examples ordering is reversed or not clear...
Pipeline assignment
You can assign the results of any pipeline into a variable. It's an array if it contains multiple items.

PowerShell

Copy
$array = 1..5 | ForEach-Object {
    "ATX-SQL-$PSItem"
}
Normally when we think of using the pipeline, we think of the typical PowerShell one-liners. We can leverage the pipeline with foreach() statements and other loops. So instead of adding items to an array in a loop, we can drop items onto the pipeline.

PowerShell

Copy
$array = foreach ( $node in (1..5))
{
    "ATX-SQL-$node"
} 

but overall awesome content
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99e524d-54e5-4119-9ebf-4fdbb7626122
* Version Independent ID: 271e2b41-af42-d4b5-3fdb-139aa5114b11
* Content: [Everything you wanted to know about arrays - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
The examples are presented in the correct order. What do you find confusing?

**Comment by AltitudeApps** [comment]
I think they were expecting the `foreach( $node in (1..5) )` example to precede the `ForEach-Object` example, something like this:

---------------

Normally when we think of using the pipeline, we think of the typical PowerShell one-liners.   _(continue exposition...)_

So instead of adding items to an array in a loop like this:
```pwsh
$array = foreach ( $node in (1..5))
{
    "ATX-SQL-$node"
}
```
We could instead send a collection of items into a pipeline, and collect the results being emitted, like this:
```pwsh

$array = 1..5 | ForEach-Object {
    "ATX-SQL-$PSItem"
}
```
![image](https://user-images.githubusercontent.com/70041186/127561569-bda815ff-0c24-4498-b373-8e20400bac43.png)
The sentence ends with the "instead" case, but the example immediately following that sentence is not the "instead" case...

**Comment by jerryKahnPerl** [comment]
yeah.. that's it.. it's not a big deal.. like I said content is excellent. was just trying to contribute with my newbie perspective.
