### ISSUE TITLE
Elaborate on valid values for Set-StrictMode

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/PowerShell-Docs#7833]
From the description in the text, I believe, it's not getting clear which values are allowed and how numerical values are interpreted.

The documentation explicitly claims to accept four different values:

- `1.0`
- `2.0`
- `3.0`
- `Latest`

This looks like being an `enum` type of value.

However, in one of the examples ([Example #3](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/set-strictmode#example-3--turn-on-strict-mode-as-version-3-0)), a value literal of `3` is being used.

This raises the following unanswered questions to my mind:

1. To which regard does the result differ, when `3` is used compared to when `3.0` is used? (Or, more generally phrased: to which regard does the result differ, when `x` is used compared to when `x.y` is used?)
1. Is `3` a valid value anyway?
1. What happens if `2.9999` will be used?

Would you mind elaborating on the valid values for `Set-StrictMode`, so these ambiguities are getting dispelled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e5d77ea-9b43-7c7e-80c8-1360b9cc13db
* Version Independent ID: 5d75ec72-b3dd-25c5-7ab8-27bc380be279
* Content: [Set-StrictMode (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-strictmode?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/Set-StrictMode.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/Set-StrictMode.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
The short answer is that it only supports a list of valid PowerShell versions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 6.1, 6.2, 7.0, 7.1 and "latest". The strictness rules are only defined for levels 1-3. Anything 3.0 or higher is considered "latest". 

The syntax for `Set-StrictMode` says that the type that the **Version** parameter expects is a `[version]` object, but the cmdlet accepts string or numeric input and attempts to convert that to a `[version]` object and then check for a valid version based on the **Major** and **Minor** properties of the object. Therefore, the value 2.9999 will fail.

```
PS> Set-StrictMode -Version 2.9999
Set-StrictMode: Cannot validate argument on parameter 'Version'. The "2.9999" argument does not contain a valid PowerShell version. Supply a valid version number and then try the command again.
```

But the value '2.0.9999' succeeds because the cmdlet only cares about the '2.0' part of the version.
