### ISSUE TITLE
RepeatHeader parameter error

### ISSUE THREAD

**Issue by filipne** [MicrosoftDocs/PowerShell-Docs#8330]
Hello, 

When I run ft  -RepeatHeader, I get :

 Format-Table : A parameter cannot be found that matches parameter name 'RepeatHeader'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a8da20-af95-ad84-a491-71c7b65a3f28
* Version Independent ID: bf057714-4790-e0db-b6eb-ad4e5e1be2b7
* Content: [Format-Table (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-table?view=powershell-7.2)
* Content Source: [reference/7.2/Microsoft.PowerShell.Utility/Format-Table.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Utility/Format-Table.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
That's because you are running Windows PowerShell 5.1 but you are reading the help for PowerShell 7.2. That parameter was added in PowerShell 6.2.

You can choose the version of PowerShell documentation from the version picker above the Table of Contents. See https://docs.microsoft.com/powershell/scripting/how-to-use-docs.
