### ISSUE TITLE
Can PowerShell 7 be an in-built app and replace PowerShell 5 by default?

### ISSUE THREAD

**Issue by b4imetu** [MicrosoftDocs/PowerShell-Docs#8344]
Can PowerShell 7 be an in-built app in Windows 11 and replace PowerShell 5 by default?

I want to use the newer PowerShell 7 but I don't want 2 PowerShell(s) in my system.

- and cmd(Command Prompt) should be deleted.

**Comment by sdwheeler** [comment]
No, Windows PowerShell 5.1 cannot be deleted. They install side-by-side. You need them installed together for the best compatibility experience. There are some Windows modules that only work in Windows PowerShell 5.1, they can be accessed using Windows Compatibility feature of PowerShell 7.2. See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility

We are working on getting PowerShell 7.x to ship in Windows so that it will be available by default. But Windows PowerShell 5.1 is not going away. And same with CMD.
