### ISSUE TITLE
About command repetition

### ISSUE THREAD

**Issue by Baikeryoyo** [MicrosoftDocs/PowerShell-Docs#8352]
As we all know, PowerShell supports both windows and Linux commands
For example, I can use ls, cat and other commands in Windows PowerShell
However, if windows and Linux have the same name
For example, the use parameters of netstat command under windows and Linux are different
Then I enter netstat under Windows PowerShell
The returned parameter is netstat under windows,
What should I do? I can use the netstat parameter of Linux under Windows PowerShell
In the same case, how can I choose freely for other commands with the same name

**Comment by sdwheeler** [comment]
PowerShell on Windows uses aliases for unix-like commands (ls, cat, etc.). The aliases run PowerShell cmdlets. For example:

```
PS> get-alias cd,ls,cat,ps

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           cd -> Set-Location
Alias           ls -> Get-ChildItem
Alias           cat -> Get-Content
Alias           ps -> Get-Process
```

In Linux, those are native commands. Those aliases are not assigned in PowerShell running on Linux so that the native command is run instead.

In Windows, `netstat` is a native command:

```
PS> Get-Command netstat

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     NETSTAT.EXE                                        10.0.1904… C:\WINDOWS\system32\NETSTAT.EXE
```

Same in Linux. PowerShell does not control the parameters that are available on native commands. The Windows version of `netstat` has many parameters in common with the Linux version but it is not 100% match. You can only use the commands (and parameters) that are available in the OS.
