### ISSUE TITLE
pkg cant be opened because apple cannot check it for malicious software

### ISSUE THREAD

**Issue by phawkshaw** [MicrosoftDocs/PowerShell-Docs#8369]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2#installation-via-direct-download

### Description of the documentation error

The document does not explain that the current 7.2.0 version does not cater for the new security features on MacOS where the OS will not allow a user to open a pkg file for installation if it cannot check it for malicious software.  

### Suggested fix

Make it clear that this issue is known (if it is) and that it is planned to be fixed in verion x.  

Provide a documented workaround for the current version 7.2.0.

**Comment by SteveL-MSFT** [comment]
This IS a known limitation because Apple requires notarization and the current build pipelines we use don't support that capability.  Work has been happening (this is a different team) to enable notarization, but I don't think we can commit to when that will be available.  In the interim, we should update the docs to indicate this is expected so they aren't surprised.  The workaround is to explicitly open the file in Finder.  I think we should just have a `Note` indicating this is known and will be addressed in the future.

**Comment by sdwheeler** [comment]
See related issues
- https://github.com/PowerShell/PowerShell/issues/10141
- https://github.com/PowerShell/PowerShell/issues/10874
