### ISSUE TITLE
Odd Behavior of the Return Keyword Should Be Better Explained

### ISSUE THREAD

**Issue by mhscott64** [MicrosoftDocs/PowerShell-Docs#8385]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_return?view=powershell-7.2

### Description of the documentation error

In the discussion of the behavior of the Return keyword when output has been... "collected", it says this:
&nbsp;&nbsp;&nbsp;&nbsp;"Please wait. Working on calculation..." string is not displayed. Instead, it is assigned to the $a variable, ...

but does NOT go on to tell us anything about where the output is stored, or how one might purge it to regain control of what is returned.   There really needs to be at least a link to a detailed discussion of where the collected data is, how it gets to the pipeline, and how you can purge it, if at all possible.

If there some valid use case where it is useful for this syntax:
&nbsp;&nbsp;&nbsp;&nbsp;return 123
to mean:
&nbsp;&nbsp;&nbsp;&nbsp;"take a Collections of things collected during the execution of the the function, append 123, and return the whole thing"
that should be explained. 

   

### Suggested fix

I don't know.  Explain how this behavior could ever be useful.

Alternately, create a new keyword, perhaps:
&nbsp;&nbsp;&nbsp;&nbsp;**returnMaybeABunchOfJunkAnd** 
that has this behavior, and change **return** to return what you specify

**Comment by sdwheeler** [comment]
The `return` keyword was really only intended for use in script-based classes, because it is the only way to return values from a class method.

Regarding the example you are citing, the article explains:

> In PowerShell, values can be returned even if the `return` keyword is not used. 
> The results of each statement are returned.

In the example function `calculation`, the function writing 2 objects to the pipeline:
- The string "Please wait. Working on calculation..."
- $value (from the return statement)

The variable `$a` receives both objects (in an array).

That is what the example is trying to warn about.

Script-based class methods work differently. If `calculation` were a class method, then only `$value` is written to the pipeline (via the `return` statement). The string object is never seen outside of the method.

**Comment by mhscott64** [comment]
I still submit the documentation should give some reason as to why it
behaves this way.  There must be some use case that is served by this ( to
me ) bizarre behavior that has cost me numerous hours of debug time across
multiple sessions.   If I must endure this pain, I would like to know why.
What is the use case that is supported here?

**Comment by sdwheeler** [comment]
The use case is for script-based class methods. Not for standard functions or scripts.

PowerShell does not prohibit you from using `return` in a normal function but it is not recommended.
