### ISSUE TITLE
about_signing page has incorrect information about file encoding

### ISSUE THREAD

**Issue by corbob** [MicrosoftDocs/PowerShell-Docs#8506]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-5.1

### Description of the documentation error

The documentation states: `The script must be saved using ASCII or UTF8NoBOM encoding. You can sign a script file that uses a different encoding. But the script fails to run or the module containing the script fails to import.` But this is incorrect as per: https://github.com/PowerShell/PowerShell/issues/3466 In fact, there are instances where the script will **not** run when it's not encoded as UTF8WithBOM.

### Suggested fix

Would be good to be clear about scenarios where signed scripts may or may not work.

**Comment by vexx32** [comment]
@sdwheeler the page information is still incorrect/misleading, and states that scripts have to be saved with UTF8**No**BOM, when that is the opposite of what folks should be doing (UTF8**WIth**BOM works fine, even with Unicode characters). AFAIK the warning here should read:

```md
The script must be saved using ASCII or UTF8WithBOM encoding. You can sign a script written in a different encoding, but the script or module will fail to run. Only UTF8WithBOM encoding allows the use of Unicode characters in the script.
```

With the additional "this was fixed in 7.2" text on the later versions' pages.
