### ISSUE TITLE
This book as a book

### ISSUE THREAD

**Issue by SynergyCoryS** [MicrosoftDocs/PowerShell-Docs#8536]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new feature or changed behavior

I want this entire PowerShell Docs site as a downloadable (and printable - aka ring binder, take it to Staples and get it bound, etc) so I can have it as a desk reference. I find paper books really helpful because they exist on my desk, and do not take up one of my monitors. Bonus points for actually publishing these as paper books. I'd give you $50 right now for this entire docs set as an actual book. Maybe Reilly or someone would publish it?
Proposed technical implementation details (optional)

Have a download PDF button for the entire PowerShell docs set. Second, think about actually publishing this as an actual book through an actual publisher. Or even have Docs sets available as books-made-to-order (maybe through Shutterfly)?

### Link to related PR in PowerShell/PowerShell repo

N/A

### Link to related Issues in PowerShell/PowerShell repo

N/A

**Comment by sdwheeler** [comment]
We have had this request several times. Our docs site has a `Download PDF` button for some of the content. For example, the Azure App Service documentation:

![image](https://user-images.githubusercontent.com/19415881/151608860-3f9eec22-e0a1-4636-8a43-331226fd9c50.png)

However, for technical reasons, that feature does not work for reference content, such as the cmdlet API reference.

What you can down is download the PowerShell-Docs source files and convert the markdown file to PDF. In some ways that is better because you can be more selective on what you want to convert.

To download the repository you can use Git to clone it or download it as a ZIP file using the `Code` button on the main page.

![image](https://user-images.githubusercontent.com/19415881/151609224-d39f9622-0237-4b20-80c6-84bfaa9834a8.png)

There are several tools that will convert markdown files to PDF. One recommendation is [Pandoc](https://pandoc.org/).

**Comment by SynergyCoryS** [comment]
Perfect, thanks. Any good book picks for PowerShell?
*Cory Sarzotti, CTS*
Programmer
*Synergy Media Group*
301 Brush Creek Road, Warrendale, PA 15086
p: 888.321.0040 <(888)%20321-0040>
c: 412-526-1705 <(412)%5261705>
www.synmediagroup.com

**Comment by sdwheeler** [comment]
We have one book in our docs today. https://docs.microsoft.com/powershell/scripting/learn/ps101/00-introduction. There is a link on the page to Leanpub where you can buy the book (name your own price).

Other than that there are lots of good books out there. It depends what you are looking for. Getting started, _Learn PowerShell in a Month of Lunches_ by Don Jones (and others) is always popular.

For more depth,
- _PowerShell in Action_ by Bruce Payette
- _PowerShell Cookbook_ by Lee Holmes

Both Bruce and Lee were some of the original developers of the PowerShell language.
