### ISSUE TITLE
Create a section on how to (if possible) setup and use VS code to debug within both Windows PS 5.1 and PS 7

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/PowerShell-Docs#8939]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

Based on https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/using-vscode?view=powershell-7.2, it is not clear:

1. How to set up VS Code to debug use BOTH Windows PS 5.1 and PS 7.
2. If the above is even possible? If not please document that.

Writing PS scripts for Windows users requires that they be used in both environments.  Whilst I have read the docs page above, I cannot determine if it is even possible to set up VS code in Widows to debug simply in both environments. For example, whilst you can add multiple terminals, there is only one "Integrated Terminal" so when debugging is started, VS Code immediately switches to the version of PS that is used for the Integrated Terminal. 

I personally have spent a lot of time trying to understand this issue without success. If it is not possible, then the documentation should say that and it would stop a lot of wasted research.

### Proposed title

Configuring Windows VS Code to debug using Windows PS 5.1 and PS 7

### Proposed location in the TOC

Debugging with Visual Studio Code ->

### List of related articles to link to

I have yet to figure out if this is possible.

**Comment by michaeltlombardi** [comment]
@swinster If I understand correctly, you want to debug the same code for both Windows PowerShell 5.1 and PowerShell 7+ in VS Code. In the documentation, the section on [choosing a version of PowerShell to use with the extension](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/using-vscode?view=powershell-7.2#choosing-a-version-of-powershell-to-use-with-the-extension) enumerates how you can switch between versions. Because of the nature of debugging and code analysis, you can only use one version at a time, but you can switch between them as needed.

Following those docs, when I open the command palette and type `Session`, I get the "PowerShell: Show Session Menu" option.

![image](https://user-images.githubusercontent.com/14190564/174809518-8efd7db8-d20f-4dd5-9a2f-35b095e6d168.png)

When I select it, I have the option to select which version I want to use.

![image](https://user-images.githubusercontent.com/14190564/174809754-626a6134-a79a-4b97-a1fb-b680defc43ba.png)

From there I can switch between PowerShell and Windows PowerShell.

Does that help?

**Comment by andschwa** [comment]
Hey @swinster, we updated to use newer VS Code APIs. You can actually get that same behavior back by _pinning_ the associated PowerShell status bar item. Here are some [instructions](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#how-do-i-change-the-powershell-version). Thanks for using the extension!

**Comment by swinster** [comment]
@andschwa - perfect - completely missed that even though it is obvious in the image above :(
