### ISSUE TITLE
New-PSDrive -Persist does not persist across reboots

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/PowerShell-Docs#9245]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

Content: https://docs.microsoft.com/powershell/module/microsoft.powershell.management/new-psdrive
Content Source: https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Management/New-PSDrive.md

### Summary

Ticket #7316 was closed without addressing the feedback about the persist parameter. Please reopen and address the feedback?

### Details

Hello, would you share where in the description of the "scope" parameter it indicates using a scope of "global" will cause the drive mapping to persist between reboots? In my experience even global variables are cleared when the powershell session is terminated.

My feedback was to put something in the article that explains how to get the drive to be persistent between reboots, and until it does so, I will consider the documentation incomplete.

I also suggested referencing the previous way to perform the same operation to help readers that are familiar with the legacy method identify "this is the new method"

I gave suggestions of edits that could make this transition from the legacy method to the new method more graceful. If you don't like any of them, might I suggest adding another Example that calls out this specific scenario?

Example 5: Create persistent and temporary drives that persist between reboots
This example shows how to create a drive mapping that persists between reboots, similar to 'net use Z: /persisitant'
[PS] C:> ---- example command ----

### Suggested Fix

Clarify how to cause a drive mapping to persist between reboots

**Comment by sdwheeler** [comment]
I think the current documentation answers your question. If the drive mapping is created with the **Persist** parameter in the Global scope it should persist across reboots. For best results, add `-Scope Global` when creating the drive mapping.

**Comment by jonwbstr** [comment]
I searched for the word reboot and do not see that word in the article.
Would you share the section you're referring to?

Why should someone equate the global scope to persisting between reboots?

**Comment by sdwheeler** [comment]
The point is that for Persist to work you must create it in the Global scope. Is that now working for you?

**Comment by sdwheeler** [comment]
After further testing, the **Persist** switch for `New-PSDrive` is not the same as `net use /persistent`. Using the **Persist** switch makes the drive mappings persist across PowerShell sessions but not through reboots. If you want the same drive mapping created after reboot, add it to your PowerShell profile script or use `net use /persistent`.

We will update the docs accordingly.

**Comment by michaeltlombardi** [comment]
Update: I was finally able to get a proper local test environment up. Here's my findings:

## Test Process

1. Create two hyper-v VMs (Server 2022, 21H2), one named `Foo` and the other named `Bar`.
2. On `Foo`, navigate to `C:\Users\Public` in the explorer.
   1. Create a new folder called `SharedData`.
   2. Set the folder's sharing permissions to allow everyone to connect without password.
3. On `Bar`, open Windows PowerShell (5.1) or PowerShell (7.2.6).
   1. ```powershell
      New-PSDrive -Persist -Name "X" -PSProvider "FileSystem" -Root "\\FOO\SharedData"
   2. Verify mapped network drive in UI and availability in PowerShell.
   3. Reboot.
   4. When the machine returns, verify the mapped network drive is still available and functional.
4. Delete VMs.

## Conclusion

Given this testing, I'm not sure that there's actually anything to document here. @jonwbstr can you provide a case where the behavior is not functioning as expected in a supported version of PowerShell and clarify those conditions?

As-is, the documentation states:

1. That the **Persist** parameter must be used to make a mapped network drive endure beyond the scope of the session it was created in.
2. That by default the mapped drive is added ephemerally _in the scope the command is run_.
3. That with the **Scope** parameter set to `Global`, you can ensure the drive is added in the global scope.
4. In order to add a persistently mapped network drive from a non-global scope, you must use the **Persist** and **Scope** parameters together.

In my testing this morning, this bore out as true and correct.

**Comment by jonwbstr** [comment]
Hi @michaeltlombardi,

I can test again, the original issue was reported 6 months ago. Maybe something has changed.

I believe I made this comparison in the other ticket
### Net use article
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/gg651155(v=ws.11)

parameter description:
> Controls the use of persistent network connections. The default is the setting used last. Deviceless connections are not persistent. Yes saves all connections as they are made, **and restores them at next logon**. No does not save the connection being made or subsequent connections. Existing connections are **restored at the next logon**.

example:
> To restore the current connections **at each logon**, regardless of future changes, type:
> net use /persistent:yes

Plain English, no interpretation or guess work needed. Description is clear the connection persists between logon's. Example of how to have connection restored at each logon. Check check check got it!

### This article:
>When your command is scoped locally, no dot-sourcing, the Persist parameter doesn't persist the creation of a PSDrive beyond the scope in which the command is running. If you're running New-PSDrive inside a script, and you want the drive to persist indefinitely, you must dot-source the script. For best results, to force a new drive to persist indefinitely, add the Scope parameter to your command, and set its value to Global.
Persist indefinitely? Is that like persisting between logon's why not just say that.

>To ensure that the drive is available outside of the script to must use the Scope parameter to create the drive in the Global scope.
outside the script. so is that in the same powershell session, the same windows session, future windows sessions too? what does this mean?

> Remember, if you use the above snippet in a script, set the Scope parameter value to "Global" to ensure the drive persists outside the current scope.
Outside the current scope again, what does this mean? same windows session, future windows sessions?

> If you close the PowerShell session and then open a new session, the temporary PSDrive: isn't available, but the persistent X: drive is available.
Okay, it means i can close the powershell session start a new one and it persists? yes? no? maybe... persist is so confusing now.

> Persist creates a Windows mapped network drive that's saved on the local computer.
Saved between longon's? saved until I logoff? Saved between powershell sessions? saved for this one powershell session but accessible outside the script? so many possible interpretations.


So... after reading all this I get that I need to use the scope parameter to persist. But persist between logon's? It never uses the word logon or anything similar. The net use command I'm using makes it very clear how to persist between logon's. This article doesn't mention persistence between logons, just this weird scope thing. The scope thing never really explained in a way I can understand it. 
Conclusion: I'll just keep using the method that with a description I can understand.

That was my thought process, but I decided to open a ticket and try to help the future visitors of this page be less confused. Hope this is helping you understand where I'm coming from.


### To review,
Assuming you are correct, please adopt the **logon session** language in the ```net use``` command, it is more understandable and familiar. Using consistent language builds a bridge from the old and familiar and the new and unfamiliar.

1) Update description to align more closely to it's predecessor
> When you scope the command locally, without dot-sourcing, the Persist parameter doesn't persist the creation of a PSDrive beyond the current **powershell session or logon session** in which you run the command. If you run New-PSDrive inside a script, and you want the new drive to persist **on next logon**, you must dot-source the script. For best results, to force a new drive to persist **on next logon**, specify Global as the value of the Scope parameter and include Persist in your command.

2) add an example that is similar to it's predecessor

**NOTE:** Is this correct? It doesn't use the global scope as previously suggested is necessary.
>To restore the current connections **at each logon**, regardless of future changes, type:
> New-PSDrive -Persist -Name "X" -PSProvider "FileSystem" -Root "\\FOO\SharedData"

**Comment by jonwbstr** [comment]
after spending a lot of time trying to digest and understand this stuff I believe there are four+ levels of drive mapping persistence. Not sure if I'm getting this right. Persist is used in multiple ways depending on other factors... Better examples needed. Here's the type of examples that would help me

1) Drive mapping is available within the current script (in the current powershell session)
    > \# from inside a script
    > New-PSDrive -Name "X" -PSProvider "FileSystem" -Root "\\Server01\Public"
2) Drive mapping is available within the current powershell session (or other sessions too? not sure)
    > \# from inside a script
    >New-PSDrive -Name "X" -PSProvider "FileSystem" -Root "\\Server01\Public" -Scope Global
    >
    > \# from prompt
    >New-PSDrive -Name "X" -PSProvider "FileSystem" -Root "\\Server01\Public"
3) Drive mapping is available to windows file explorer, and other powershell sessions (does not persist between logon's?) ???
    > New-PSDrive -Persist -Name "X" -PSProvider "FileSystem" -Root "\\Server01\Public"
4) Drive mapping is available to windows file explorer and other powershell sessions between logon's ???
    > New-PSDrive -Persist -Name "X" -PSProvider "FileSystem" -Root "\\Server01\Public" -Scope Global

**Comment by michaeltlombardi** [comment]
# Comment Reply

Hi, @jonwbstr, thanks for the detailed replies! I spent some more time today going through my test case and wanted to write up a thorough response for you.

I'll address your second reply first, leaving aside the way `net use` works for a moment:

1. Correct. When you use `New-PSDrive` in PowerShell, you get an ephemeral (non-persisting) drive in the current scope. If you use `New-PSDrive` without the **Scope** parameter in a script, the drive exists in that script's scope only.
1. When you use the **Scope** parameter set to `Global`, the drive is created in the Global scope. In [about_Scopes][01], the documentation says:

   > Global: The scope that is in effect when PowerShell starts or when you create a new session or runspace. Variables and functions that are present when PowerShell starts have been created in the global scope, such as automatic variables and preference variables. The variables, aliases, and functions in your PowerShell profiles are also created in the global scope. The global scope is the root parent scope in a session.

   So what the **Scope** parameter of `New-PSDrive` allows you to do is get around the limitations of how scoping in PowerShell works by registering the PSDrive in the Global scope instead of the script's scope.

   This makes the created drive available in the Global scope for that session.
1. When you use the **Persist** parameter in the Global scope, the mapped drive is available to the Windows File Explorer and other PowerShell sessions.

   If you're using `New-PSDrive` outside of the Global scope (as in a script or function instead of directly in the terminal), you need to make sure it is created in the Global scope. The [documentation for the Persist parameter][02] says:

   > When you scope the command locally, without dot-sourcing, the **Persist** parameter doesn't persist the creation of a **PSDrive** beyond the scope in which you run the command. If you run `New-PSDrive` inside a script, and you want the new drive to persist indefinitely, you must dot-source the script. For best results, to force a new drive to persist, specify `Global` as the value of the **Scope** parameter and include **Persist** in your command.

   Which is a restatement of the general behavior for the cmdlet: `New-PSDrive` only affects the current scope unless you use alter the scope.
1. You don't need to specify the **Scope** parameter to persist the drive across logins or reboots in my testing. If the command runs in the Global scope, is run in a script dot-sourced into the Global scope, or specifies `Global` with the **Scope** parameter, the effect is the same.

## First Comment

Addressing your first comment now:

> Persist indefinitely? Is that like persisting between logon's why not just say that.

The context of `net use` is different from `New-PSDrive`. The documentation you quoted is clarifying that the drive will indeed persist indefinitely, across sessions (including logons in my testing), as compared to not using the parameter, which has the drive mapping only for the duration of that session.

> outside the script. So is that in the same powershell session, the same windows session, future windows sessions too? what does this mean?
>
> ...
>
> > Outside the current scope again, what does this mean? same windows session, future windows sessions?

This refers specifically to the concept of [scoping][01] in PowerShell. To make a **PSDrive** available outside the scope `New-PSDrive` is executed in, you can use the **Scope** parameter to ensure it's created in the Global scope. You can also dot-source the the script when executing it from the Global scope for the same effect. The documentation is clarifying that using the **Scope** parameter is a more reliable method of doing this - it means you don't have to remember to dot-source the script. It's also explicit.

> Outside the current scope again, what does this mean? same windows session, future windows sessions?

In my testing it _does_ persist between logons. I will need you to provide a repro of a case where this doesn't happen - otherwise, the docs appear to be correct on this point.

> Saved between longon's? saved until I logoff? Saved between powershell sessions? saved for this one powershell session but accessible outside the script? so many possible interpretations.
> 
> So... after reading all this I get that I need to use the scope parameter to persist. But persist between logon's? It never uses the word logon or anything similar. The net use command I'm using makes it very clear how to persist between logon's. This article doesn't mention persistence between logons, just this weird scope thing. The scope thing never really explained in a way I can understand it.
> Conclusion: I'll just keep using the method that with a description I can understand.

It does not use the word logon because (again, in my testing) there's no distinction to make between mapped network drives persistent across sessions and logons. The documentation for the parameter states:

> Indicates that this cmdlet creates a Windows mapped network drive. The Persist parameter is only available on Windows.
> 
> Mapped network drives are saved in Windows on the local computer. They're persistent, not session-specific, and can be viewed and managed in File Explorer and other tools.

Unless you can provide me with a reproducible case where a mappped drive created with `New-PSDrive -Persist` in the Global scope _doesn't_ persist across logons, I don't think adding language about logons to the document will make things clearer.

However, while the documentation does link to [about_Scopes][01] in the **Scope** parameter, it doesn't link to it in the description or the **Persist** parameter. I think the language about scoping (and, particularly, linking to the relevant documentation) should be improved.

The existing examples cover persistent and temporary mapped network drives and clarify when and how to handle scoping. I don't think additional examples will be useful, unless there is some edge case that causes mapped network drives created with `New-PSDrive -Persist` in the Global scope to not persist across logons.

## Screenshots

The following screenshots show the commands and context for my tests, including their results. What they don't show is that the mapped network drive persisted across reboots, though in my testing they did.

### Global scope

In these cases, the commands were run directly from the Global scope.

#### Temporary drive

```powershell
Get-PSDrive -PSProvider FileSystem | ft Name, Root
$Parameters = @{
  Name       = 'X'
  PSProvider = 'FileSystem'
  Root       = '<Your UNC Path>'
}
$x = New-PSDrive @Parameters
Get-PSDrive -PSProvider FileSystem | ft Name, Root
```

![global-non-persist](https://user-images.githubusercontent.com/14190564/193123580-04cbf580-4703-4cd2-be6e-b1c8bab54805.PNG)

#### Persistent drive

```powershell
Get-PSDrive -PSProvider FileSystem | ft Name, Root
$Parameters = @{
  Name       = 'X'
  PSProvider = 'FileSystem'
  Root       = '<Your UNC Path>'
  Persist    = $true
}
$x = New-PSDrive @Parameters
Get-PSDrive -PSProvider FileSystem | ft Name, Root
```

![global-persist](https://user-images.githubusercontent.com/14190564/193124254-37435aef-d4dc-450d-9710-a34e9ebf0709.PNG)

### Script

The examples here all use the same script, which I called `MapDrive.ps1`:

```powershell
param(
  [string] $Name,
  [string] $PSProvider,
  [string] $Root,
  [switch] $Persist,
  [string] $Scope
)

New-PSDrive @PSBoundParameters |
  Format-Table Name, Root
```

#### Temporary drive, dot-sourced into global scope

```powershell
Get-PSDrive -PSProvider FileSystem | ft Name, Root
$Parameters = @{
  Name       = 'X'
  PSProvider = 'FileSystem'
  Root       = '<Your UNC Path>'
}
. .\MapDrive.ps1 @Parameters
Get-PSDrive -PSProvider FileSystem | ft Name, Root
```

![script-dot-source-non-persist](https://user-images.githubusercontent.com/14190564/193129262-ecf4be75-c1f8-4647-821a-5e600904bdcd.PNG)

#### Persistent drive, dot-sourced into global scope

```powershell
Get-PSDrive -PSProvider FileSystem | ft Name, Root
$Parameters = @{
  Name       = 'X'
  PSProvider = 'FileSystem'
  Root       = '<Your UNC Path>'
  Persist    = $true
}
. .\MapDrive.ps1 @Parameters
Get-PSDrive -PSProvider FileSystem | ft Name, Root
```

![script-dot-source-persist](https://user-images.githubusercontent.com/14190564/193126607-e6783e7f-55d3-4085-b237-361f801f65a5.PNG)

#### Temporary drive, global with scope parameter

```powershell
Get-PSDrive -PSProvider FileSystem | ft Name, Root
$Parameters = @{
  Name       = 'X'
  PSProvider = 'FileSystem'
  Root       = '<Your UNC Path>'
  Scope      = 'Global'
}
.\MapDrive.ps1 @Parameters
Get-PSDrive -PSProvider FileSystem | ft Name, Root
```

![script-global-scope-non-persist](https://user-images.githubusercontent.com/14190564/193126679-2d128a32-51b9-43f5-8dfa-42b0974f3ff8.PNG)

#### Persistent drive, global with scope parameter

```powershell
Get-PSDrive -PSProvider FileSystem | ft Name, Root
$Parameters = @{
  Name       = 'X'
  PSProvider = 'FileSystem'
  Root       = '<Your UNC Path>'
  Persist    = $true
  Scope      = 'Global'
}
.\MapDrive.ps1 @Parameters
Get-PSDrive -PSProvider FileSystem | ft Name, Root
```

![script-global-scope-persist](https://user-images.githubusercontent.com/14190564/193128287-4a21e308-4039-4da6-80e3-3875bc3a527e.PNG)

#### Temporary drive, script scope

```powershell
Get-PSDrive -PSProvider FileSystem | ft Name, Root
$Parameters = @{
  Name       = 'X'
  PSProvider = 'FileSystem'
  Root       = '<Your UNC Path>'
}
.\MapDrive.ps1 @Parameters
Get-PSDrive -PSProvider FileSystem | ft Name, Root
```

![script-non-persist](https://user-images.githubusercontent.com/14190564/193127067-4918d701-6561-4db8-afd4-b618286c51b7.PNG)


#### Persistent drive, script scope

This is the only example where the mapped drive did not persist for me - because it was not created in the Global scope.

```powershell
Get-PSDrive -PSProvider FileSystem | ft Name, Root
$Parameters = @{
  Name       = 'X'
  PSProvider = 'FileSystem'
  Root       = '<Your UNC Path>'
  Persist    = $true
}
.\MapDrive.ps1 @Parameters
Get-PSDrive -PSProvider FileSystem | ft Name, Root
```

![script-persist-no-scope](https://user-images.githubusercontent.com/14190564/193127092-d4bd066e-f6b4-441f-883f-6d331e38d1ac.PNG)


[01]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_scopes
[02]: https://learn.microsoft.com/powershell/module/microsoft.powershell.management/new-psdrive#-persist
