### ISSUE TITLE
Use correct version in examples for `Enable-PSRemoting`

### ISSUE THREAD

**Issue by peetrike** [MicrosoftDocs/PowerShell-Docs#9411]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/powershell/module/microsoft.powershell.core/enable-psremoting?view=powershell-7.2
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.2/Microsoft.PowerShell.Core/Enable-PSRemoting.md

### Summary

This page is supposed to be version-specific.  It's a bit odd to see version 7.2 page refer to version 6.x and version 7-preview.

It might happen, that other v7-specific pages have same problem.

### Suggested Fix

replace version references to current version.

**Comment by michaeltlombardi** [comment]
The information that it's covering is explaining how `Enable-PSRemoting` behaves when multiple versions of PowerShell are installed on a system. While the example versions refer to older versions, the behavior is the same. Was the inclusion of these versions confusing, or just noticeable, or something else?

While I think we could do an irregular update cadence to this file, I don't think making the versions always match the documentation version is necessarily helpful, since it will still need to reference multiple versions (at least one of which necessarily won't be the current version).
