### ISSUE TITLE
Grouping Operator Behavior for variable assignments not documented

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs#9489]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators?view=powershell-7.3#grouping-operator--

Should also be noted and referenced https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_assignment_operators?view=powershell-7.3

### Summary

The grouping operator `()` has additional functionality typically known as "variable squeezing" which is not documented here. For instance:
```powershell
$i = 5 #Outputs nothing
($i=5) #Outputs 5
$($i=5) #Outputs nothing (is a subexpression, not a squeeze)

$i++ #Outputs nothing but increments to 6
($i++) #Outputs 6 (the value before addition) but increments to 7
(++$i) #Increments then outputs, result is 8
$i #Is now 8

if ($x=$true) {'ok'} #Outputs OK because the assignment operation is also output
$x #Outputs $true
```

### Details

Prior Art: This psscriptanalyzer notes "clang style assignment" as supported as long as it is doubly-wrapped to indicate the intent
https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/possibleincorrectusageofassignmentoperator?view=ps-modules#implicit-suppresion-using-clang-style

### Suggested Fix

Document this additional behavior as it is currently obscure and idiotmatic.

**Comment by sdwheeler** [comment]
@JustinGrote You bring up some interesting points here. I not sure I like the term "variable squeezing", but I am struggling with how to describe it. The Language Spec talks about it in terms of side effects. See the following references:
- The opening paragraphs of https://learn.microsoft.com/powershell/scripting/lang-spec/chapter-07
- Grouping parentheses - https://learn.microsoft.com/powershell/scripting/lang-spec/chapter-07#711-grouping-parentheses
- The $() operator - https://learn.microsoft.com/powershell/scripting/lang-spec/chapter-07#716--operator

I am open to suggestions for better descriptions.

**Comment by JustinGrote** [comment]
Good find. I dislike the term side effects to describe normal behavior like assignment. The whole conceptual idea of being presented here that doing an assignment is a quote weird Behavior and using parentheses disables that weird Behavior is the wrong message. Variable squeezing is the term that was just described to me by the person who showed me this, but I'm not married to the term. I feel like a better way to describe this would be assignment pass through, as the term pass through is very familiar to Powershell users and this would be mimicking similar Behavior as using the pass-through parameters that are commonly present on a command

I also don't personally endorse or prefer this style of programming, but I was surprised to find on Discord that this is a more commonly used method than I expected, so I think it's important to document it so anyone who sees it, doesn't see it as a mistake like I did initially

**Comment by sdwheeler** [comment]
> a better way to describe this would be assignment pass through

I like that.

**Comment by michaeltlombardi** [comment]
I think pass through makes the most sense to describe this behavior, because it's clear about what it's causing to happen and doesn't require outside context or prior knowledge.

Aside: When the language spec talks about side effects, it's doing so in the computer science lexicon, that is:

> ...an operation, function or expression [that] has any observable effect other than its primary effect of returning a value to the invoker of the operation.
>
> [Source (Wikipedia)](https://en.m.wikipedia.org/wiki/Side_effect_(computer_science))

In that context, it's accurate, but if we find ourselves needing to break out a domain-specific dictionary to explain why we're using terminology there's a good chance it's not the right term to use for this context.

**Comment by JustinGrote** [comment]
> > ...an operation, function or expression [that] has any observable effect other than its primary effect of returning a value to the invoker of the operation.

The funny thing here is the observable "effect" is that a value is simply not returned, so is the absense of that primary function considered a side effect? It's a weird meta-semantic, but not what I would typically think of as a side effect like the other examples in that article such as executing a remote operation or setting a state variable. Regardless, we are agreed it's probably the improper terminology.


I would say something like this as a start as a third "bullet point" under `However, in PowerShell, there are additional behaviors.`

* An assignment operation (ex. `$i = 2`) normally does not return anything, however, when the grouping construct is used to enclose an assignment operation, the result of the assignment will be passed through. The behavior can vary depending upon the operator used: 
```
$i = 5 #Outputs nothing
($i=5) #Outputs 5
$($i=5) #Outputs nothing (is a subexpression, not a squeeze)

$i++ #Outputs nothing but increments to 6
($i++) #Outputs 6 (the value before addition) but increments to 7
(++$i) #Increments then outputs, result is 8
$i #Is now 8

if ($x=$true) {'ok'} #Outputs OK because the assignment operation is also output
$x #Outputs $true
```

This use of the grouping construct [can be a useful shorthand in if statements](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/possibleincorrectusageofassignmentoperator?view=ps-modules#implicit-suppresion-using-clang-style), however it can be difficult to debug with breakpoints and is generally not recommended over separating a variable assignment and the use of that variable.

**Comment by mklement0** [comment]
Good discussion; let me propose a more didactic approach:

----

`(...)` turns variable assignments (e.g., `$var = 1 + 2`)  into _expressions_:

That is, when you enclose a variable assignment in `(...)`, the assigned-to variable's new value  is _passed through_, i.e. it becomes the operator's output, even though assignments in isolation do not produce output.

This enables you to both save a value participating in a larger expression or command for later use, e.g.:

```powershell
($var = 1 + 2) -eq 3  # -> $true
```
```powershell
$var = 1
($var += 2) -eq 3  # -> $true
```

You can also use this technique In the context of an `if` statement, where the output is implicitly coerced to `$true` or `$false`:

```powershell
if ($textFiles = Get-ChildItem *.txt) { <# ... work with $textFiles #> )
```

If no files match, the `Get-ChildItem` command returns nothing and assigns nothing to `$textFiles`, which is considered `$false` in a Boolean context; otherwise, if one or more file-info objects are assigned to `$textFiles`, the conditional evaluates to `$true`, and you can work with the value of `$textFiles` in the body of the `if` statement.

Note: 
 * While this technique is convenient and concise, it can lead to confusion between `=`, the assignment operator and `-eq`, the equality-comparison operator.

The above not only applies to assignments that use `=` and its compound variations (such as `+=`, as shown above), but also to the increment and decrement operators, `++` and `--`, and it notably matters whether you use the prefix or the postfix form: the prefix form passes the _new_ value through, whereas the postfix form passes the _old_ value through:

```powershell
# Prefix form
$i = 0; (++$i)  # -> 1 (new value); $i now contains 1

# Postfix form
$i = 0; ($i++)  # -> 0 (old value); ; $i now contains 1
```
