### ISSUE TITLE
invoke-command:  get-childitem - example 12 doesn't work

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#9873]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-7.3#example-12-use-the-args-automatic-variable-in-a-script-block

### Summary

Example 12 doesn't work because of a long standing display bug.  Get-childitem doesn't display correctly over invoke-command.

### Details

```powershell
# elevated prompt and localhost
$parameters = @{
    ComputerName = 'localhost'
    ScriptBlock  = { Get-ChildItem $args[0] $args[1] }
    ArgumentList = 'C:\Test', '*.txt*'
}
Invoke-Command @parameters


    Directory: C:\Test

Mode                 LastWriteTime         Length Name                               PSComputerName
----                 -------------         ------ ----                               --------------
                                                                                     localhost
                                                                                     localhost
                                                                                     localhost
```

### Suggested Fix

Maybe you should add a warning about this.

**Comment by michaeltlombardi** [comment]
Thanks for filing this, @jszabo98. Unfortunately, this is a bug that affects a partial subset of users and we don't document bugs unless they're marked as won't-fix (in other words, they're known limitations).

As described in PowerShell/PowerShell#10759, this bugged behavior is visible when using `Invoke-Command` from a PowerShell 7+ session to a Windows PowerShell session. When remoting to PowerShell instead of Windows PowerShell, the behavior is as documented. When remoting from Windows PowerShell to Windows PowerShell, the behavior is as documented.

**Comment by jszabo98** [comment]
I'm not trying to get this reopened, but my perspective is that after several years, this bug isn't likely be fixed, and for now setting up a powershell 7 endpoint to connect to with invoke-command is unlikely.
